### ISSUE TITLE
RMQ Close Connection is deprecated

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#1066]
**Is your feature request related to a problem? Please describe.**
We get the following build warning from the .NET RMQ client

RMQMessageGateway.cs(139,21): warning CS0618: 'IConnection.AutoClose' is obsolete: 'Please explicitly close connections instead.' [/Users/ian.cooper/CSharpProjects/github/BrighterCommand/Brighter/src/Paramore.Brighter.MessagingGateway.RMQ/Paramore.Brighter.MessagingGateway.RMQ.csproj]

**Describe the solution you'd like**
We need to explicitly close connections, both when we have an error and at shutdown

**Describe alternatives you've considered**
The feature is now 'do nothing' AFAIK, so there is a danger we leak connections and should close

**Additional context**

**Comment by holytshirt** [comment]
Fixed in brighter V8 and in master for V9
