### ISSUE TITLE
Microsoft Dapr

### ISSUE THREAD

**Issue by jpiquot** [BrighterCommand/Brighter#1101]
Hi,

Any plan to support Microsoft Dapr state storage and pub/sub features?

[Dapr Home](https://dapr.io/)
[Dapr Github](https://github.com/dapr/dapr)
[Dapr DotNet Github](https://github.com/dapr/dotnet-sdk)

**Comment by iancooper** [comment]
@jpiquot Good question. Dapr is so new that our thoughts about this are very nascent. Hoping to get some more time over the next couple of weeks to understand what it might mean to us

**Comment by iancooper** [comment]
I'm going to park this one. As Dapr is really just an abstraction over transports it has the same role as Brighter. It's more likely that we would deploy Brighter as a sidecar.
