### ISSUE TITLE
Variable reference not used

### ISSUE THREAD

**Issue by gcaferra** [BrighterCommand/Brighter#1375]
https://github.com/BrighterCommand/Brighter/blob/e76b912a171f9e7b90c224173d606648a74525c5/src/Paramore.Brighter.MessagingGateway.RMQ/PullConsumer.cs#L87

as seen above a local copy of messages is created but the following loop is using the field

**Comment by holytshirt** [comment]
Thanks @gcaferra do you want to do a pull request?

**Comment by holytshirt** [comment]
Don't worry, I'll just delete the line. Thanks so much for finding it!

**Comment by holytshirt** [comment]
Done
