### ISSUE TITLE
V9 NoOpOutbox does not work

### ISSUE THREAD

**Issue by holytshirt** [BrighterCommand/Brighter#1390]
### Describe the bug
The NoOpOutbox does not work
https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter/NoOpOutbox.cs

### To Reproduce
Configure Brighter with NoOpOutbox and Post() message.
You'll get a null exception

### Further technical details
- Brighter version: 9.0.0

**Comment by iancooper** [comment]
Thanks @holytshirt Top of my list.

**Comment by iancooper** [comment]
See #1394

**Comment by iancooper** [comment]
PS Design is loosely based on the Microsoft.Extensions.Caching InMemoryCache i.e. threads for sweep and compaction.
