### ISSUE TITLE
Bug: Missing Tests for MSSQL Gateway

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#1409]
### Describe the bug
The MSSQL has no regression tests

### To Reproduce
Look at the project structure, we might expect them to be in the MSSQL tests project under a MessagingGateway folder, but they are not there

### Further technical details
Whilst a transport may use Test After as opposed to Test First (because you are writing a plugin not designing contract first) we do need to ensure that we don't regress a transport when we make changes to the core, which does require automated tests we can run as part of our CI process

**Comment by iancooper** [comment]
@preardon Have we moved the dial on this one at all?

**Comment by preardon** [comment]
@iancooper I wasn't looking at this one, I can pick it up if you would like and can give it the Azure.Identity Treatment while I'm there if you like

**Comment by iancooper** [comment]
@preardon Be cool if you could, I'd like to kill any bugs we have related to areas we are working on. (I'd like to kill anything marked Bug, but this is a start).

**Comment by preardon** [comment]
@iancooper is Anyone going to get upset, If I modify the Test Helped to point to a docker instance instead of The local one currently being used for Inbox and OutBox

**Comment by preardon** [comment]
@iancooper Found a few bugs will fix while I'm in the Ditch

**Comment by iancooper** [comment]
@preardon No, that's a good idea.

**Comment by iancooper** [comment]
> @iancooper Found a few bugs will fix while I'm in the Ditch

Yeah, I thought that might happen. Hoping to have the logging review done today

**Comment by preardon** [comment]
@iancooper Have we had issues with v9 and Deserialization of Messages in General?

**Comment by preardon** [comment]
Logged a Bug and PR for the Above #1509 and will continue with this after the fix is in

**Comment by preardon** [comment]
@iancooper I'll have a look, can we spin up Docker in your Pipeline to connect these to?

**Comment by preardon** [comment]
@iancooper I've found it and Pushed a change

**Comment by iancooper** [comment]
Closed this, thanks @preardon
