### ISSUE TITLE
Support non-RTTI-based handler lookup

### ISSUE THREAD

**Issue by benjamin-hodgson** [BrighterCommand/Brighter#144]
See discussion in #116.

We think it might be a good idea to support a `GetKey()` (or similar) operation on a message, so that users can customise handler look-up. By default this function would just return `this.GetType()`. This would allow us to support `Publish(IEnumerable<Event> events)`.

In practice, the message dispatcher would still have to downcast your event (to `MyEvent`) and its handlers (to `IHandleRequests<MyEvent>`) after it's looked them up - how would this work with `GetKey()`? I leave that question open for people with greater familiarity with `CommandProcessor`'s implementation.

**Comment by iancooper** [comment]
Thanks. We can ponder if this change solves the problem of IEnumerable<Event> and try that instead.

**Comment by Red-F** [comment]
See my comment under the original #116

**Comment by iancooper** [comment]
Closed as we just use the workaround in #116
