### ISSUE TITLE
ASB - add support for Azure Managed Service Identities for connections

### ISSUE THREAD

**Issue by penderi** [BrighterCommand/Brighter#1443]
Azure services typically use MSI to control access to resource from services. Current ASB implementation allows only a connections tring.

Allow Azure connections (via config) to specify MSI connection

mentioned in #1438

**Comment by preardon** [comment]
@penderi I would be more than happy to pick this one up

**Comment by preardon** [comment]
@penderi  From what I can see this isn't required as it comes out of the box with the Topic Client (via the Connection String "Endpoint=sb://xxx.servicebus.windows.net/;Authentication=Managed Identity" )

See  ( https://github.com/Azure/azure-sdk-for-net/blob/1e2b25c14c307be96365c45b0f47dbdc2df03649/sdk/servicebus/Microsoft.Azure.ServiceBus/src/ServiceBusConnection.cs#L19 )

**Comment by penderi** [comment]
@iancooper I raised this thinking we've an issue. We're confident it should be ok - I propose we close. If we see any issue we'll address it and re-open.

**Comment by preardon** [comment]
@iancooper This can be closed as it was already supported
