### ISSUE TITLE
Update MsSql Inbox and Outbox to use Azure.Identity (MSAL)

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1491]
The Current MsSQL inbox and outboxes only current support SQL Authentication and no the newer MSAL Libraries

I would like a config switch to allow the use of Token Based Authentication to the SQL Server (MSAL)

I do no believe that there are any alternate solutions.

**Comment by preardon** [comment]
@iancooper If you're happy with this I'll get it done in the next few days mate

**Comment by iancooper** [comment]
@preardon Very happy mate. Thanks for adding that.

**Comment by preardon** [comment]
Looking at this again, I'm going to do a quick refactor to plumb through Cancellation tokens to all Async Methods

**Comment by preardon** [comment]
@iancooper Is there any Documentation you want be to update with these Configuration Items?

**Comment by iancooper** [comment]
We use ReadTheDocs at the moment, and you can find the source in a the docs directory. It might be worth switching to GitBook at some point. I don't think we have per-Db documentation, we tend to rely on tests and samples, so it depends whether you think it needs it, as someone who uses that platform
