### ISSUE TITLE
AWSSQS - SqsSubscription Constructor parameters incorrectly assigned

### ISSUE THREAD

**Issue by honkuan86** [BrighterCommand/Brighter#1516]
### Describe the bug
Found that the SqsSubscription constructor params (bufferSize, noOfPerformers) is assigned incorrectly to the base Subscription class, causing the Dispatcher always create the performers according to the value of bufferSize.

### To Reproduce
Run the AWS sample project should be able to reproduce it.

### Exceptions (if any)
No exception, as it is a behavior bug.

**Comment by honkuan86** [comment]
@iancooper , I'll pick this up

**Comment by honkuan86** [comment]
@iancooper , I can pick this up.

**Comment by iancooper** [comment]
@honkuan86 Please do. Thanks for spotting this one.
