### ISSUE TITLE
Messages that are retried too many times should move to DLQ if there is one

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#1519]
### Describe the bug
To avoid a poison message scenario we only allow you to requeue a message x times. In the event that you are tried beyond that count we ack you, so you won't go onto any DLQ.

In addition, we treat all user code exceptions that bubble out of the handler as application errors i.e. we just ack and move on. We might chose to let you opt to retry a failure that you think is timing related using our requeue option (attribute?)

### To Reproduce
Create a handler that throws a user code exception, it will not reach the DLQ

**Comment by preardon** [comment]
Hey mate, I am happy to pick this one up if you want.

From what I can see, in the Message Pump, on When Catching Generic Exceptions we Log an Error, Exit the Catch Block and then the Code Continues on to Acknowledge.

I'm Guessing in the Catch Block we want to call Reject Message and then Continue on to the Next Iteration of the Loop? Perhaps Increment The Unacceptable Message Limit as well

**Comment by iancooper** [comment]
@preardon Feel free to give it a go (separate PR please).

So, if the channel supports a DLQ, we need to count the number of times you requeue a message. To do that, we need to: 

* Maintain a count in the header of the number of times it has been requeued. (We might do that already, nagging suspicion). * Increment the counter on requeue
* When the count exceeds a user-defined value (set in the base Subscription class) - send to the DLQ via Reject
* If we send to the DLQ, increment the unacceptable message limit.

At some point we need to look at the unacceptable message limit, because it really needs to be a window. But DON'T tackle that here, just get the DLQ on enough requeues working

**Comment by iancooper** [comment]
PS Channel is your friend here I suspect. It wraps the per-platform message consumers. So if you want to put some generic code i.e. incrementing the count in the header, this is where you would do it.

**Comment by iancooper** [comment]
@preardon Yes, we have a HandledCount on the message and the pump currently discards when hit, but should reject

The wrinkle here is that HandledCount is used for the explicit DeferMessage exception that can be raised by a consumer. That is how you should reject to retry the message (don't forget you just have a handler, not the consumer, so you can't reject, instead you throw a specific exception

**Comment by iancooper** [comment]
@preardon I can do a Zoom call later if you want more help understanding this. But have a stab, and let's see what it looks like.

As ever, its Core, so TDD please :-D

**Comment by iancooper** [comment]
PS, The Hash Code here should be based on Id, Topic, and Type. We should kill the other elements as part of this. It doesn't make sense to test messages for equality based on transient variables:

 public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = Id.GetHashCode();
                hashCode = (hashCode * 397) ^ (Topic != null ? Topic.GetHashCode() : 0);
                hashCode = (hashCode * 397) ^ (int)MessageType;
                hashCode = (hashCode * 397) ^ TimeStamp.GetHashCode();
                hashCode = (hashCode * 397) ^ HandledCount.GetHashCode();
                hashCode = (hashCode * 397) ^ DelayedMilliseconds.GetHashCode();
                return hashCode;
            }
        }

**Comment by iancooper** [comment]
It will need a little bit of tweaking: you are really trying to get a DeferMessageAction exception to have an upper limit on the number of times it gets sent and move to a DLQ of that is exceeded over discard.

We probably need to document that you can throw DeferMessageAction to requeue a message for later processing

**Comment by preardon** [comment]
@iancooper I think I've found an issue in one of your core Tests (When_An_Unacceptable_Message_Is_Recieved), it can't map "" to MyEvent, I'll put a fix in if this isn't intended

**Comment by preardon** [comment]
@iancooper The Deeper I go the More Interesting this gets. I am using ASB, Kafka, and SQS as my 3 Examples.

At the Minute ASB Grabs a Producer and Sends with Delay (This is Possibly going to Cause me issues due to not being able to have Async Handlers and Producers), Also I do Wonder if I should Change this Behaviour if AckOnRead is turned on, to Just Abandon the Lock (which will use ASB DLQ) and will work through the Pump Otherwise.

Kafka is a No-Op as its Immutable

SQS Changes Visibility (which is also what you do for Reject, _hasDlq

Anyway, I'm assuming you are fine with me to Increment the Handled Count in the Pump?

**Comment by preardon** [comment]
> @preardon I can do a Zoom call later if you want more help understanding this. But have a stab, and let's see what it looks like.
> 
> As ever, its Core, so TDD please :-D

I could Handle 10 minutes of your time if you've got it for Clarification, Otherwise I'll charge Ahead

**Comment by preardon** [comment]
> It will need a little bit of tweaking: you are really trying to get a DeferMessageAction exception to have an upper limit on the number of times it gets sent and move to a DLQ of that is exceeded over discard.
> 
> We probably need to document that you can throw DeferMessageAction to requeue a message for later processing

Are you saying that We only want to Requeue if we the handler throws a DeferMessageAction? and requeue everything based on the Requeue count of the Channel?

**Comment by iancooper** [comment]
@preardon What time works for you, might be worth a chat as I have not fully thought through any design and we may want to explore together

**Comment by preardon** [comment]
@iancooper I should be able to do times between 11:00 and 11:30 or 12:00 to 2pm let me know if these work for you

**Comment by iancooper** [comment]
Thanks @preardon
