### ISSUE TITLE
System Text JsonSerializer does not de-serialize Dictionary<string, object> faithfully

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#1538]
### Describe the bug
System Text JsonSerializer does not de-serialize Dictionary<string, object> faithfully.

When serializing Dictionary<string, object>, JsonSerializer works as expected, but when converting back, the object is a value type called JsonElement, with hints as to the type info. Because we can't process this, we have to convert back to an object.

This bug impacts all Outbox code that moved to JsonSerializer with v9.

EventStore has been fixed, but the fix now needs to be generic i.e. we need the reader and writer methods from event store to move to Brighter and be used for all reading and writing to an Outbox

### To Reproduce
A test for the header properties of a message deserialized from the Outbox will show this one up

**Comment by preardon** [comment]
@iancooper I will have a look at this now if you like

**Comment by iancooper** [comment]
@preardon In progress under my 'fix red tests' work, will ping you as a reviewer when done
