### ISSUE TITLE
The Azure Service Bus Transport does not support Rejecting

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1540]
At the Current point in time the Azure Service Bus Transport does not support Rejecting the Message

Line 211 of AzureServiceBusConsumer
`s_logger.LogWarning("Reject method NOT IMPLEMENTED.");`

and as such messages will not find their way to the Dead Letter Queue

**Comment by preardon** [comment]
I've just submitted PR #1541 For this

**Comment by preardon** [comment]
@iancooper I am under the Assumption (Based on SQS Gateway) that we want the Reject Command to Put the Letter on the Dead Letter Queue instead of a Just Abandoning the Lock (Which would either Retry or Dead Letter dependant on retires)?

**Comment by iancooper** [comment]
@preardon Yes, we have an explicit requeue op for 'make this available to others' (although its common to delay to allow transient issues to correct). Reject means don't re-queue this and put on the DLQ if we have one.

**Comment by preardon** [comment]
@iancooper Excellent, the PR #1541 Should Give us this for ASB

**Comment by iancooper** [comment]
@preardon Cool, will look at lunch or after close of play today
