### ISSUE TITLE
When Adding Service Activator, if you Specify BrighterMessaging it does not register an Async Handler Factory

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1545]
When Configuring as such
services.AddServiceActivator(options => { options.Subscriptions = subscriptions; options.ChannelFactory = new AzureServiceBusChannelFactory(asbConsumerFactory); var outBox = new InMemoryOutbox(); options.BrighterMessaging = new BrighterMessaging(outBox, AzureServiceBusMessageProducerFactory.Get(asbConfig)); }).AutoFromAssemblies();

Specifically when adding the BrighterMessaging (So that my Handler can Post commands as well)

We end up hitting the following (ServiceCollectionExtensions.cs Line 55)
`
if (options.ChannelFactory is null)
{
//TODO: Need to add async outbox

            taskQueuesBuilder = options.BrighterMessaging == null
                ? messagingBuilder.NoTaskQueues()
                : messagingBuilder.TaskQueues(new MessagingConfiguration(options.BrighterMessaging.OutBox,
                    options.BrighterMessaging.AsyncOutBox, options.BrighterMessaging.Producer,
                    options.BrighterMessaging.AsyncProducer, messageMapperRegistry));
        }
        else
        {
            taskQueuesBuilder = options.BrighterMessaging == null
                ? messagingBuilder.NoTaskQueues()
                : messagingBuilder.RequestReplyQueues(new MessagingConfiguration(options.BrighterMessaging.OutBox,
                    options.BrighterMessaging.Producer, messageMapperRegistry, responseChannelFactory: options.ChannelFactory));
        }
`

The issues with this is if we Provide a ChannelFactory (Which we must for consuming) And We Specify BrighterMessage (Which we need for Producing), We end up with RequestReplyQueues

and then when we build (CommandProcessorBuilder.cs line 224)
`
if (!(_useTaskQueues || _useRequestReplyQueues))
{
return new CommandProcessor(

                subscriberRegistry: _registry,
                handlerFactory: _handlerFactory,
                asyncHandlerFactory: _asyncHandlerFactory,
                requestContextFactory: _requestContextFactory,
                policyRegistry: _policyRegistry,
                featureSwitchRegistry: _featureSwitchRegistry);
        }
        else if (_useTaskQueues)
        {
            return new CommandProcessor(
                subscriberRegistry: _registry,
                handlerFactory: _handlerFactory,
                asyncHandlerFactory: _asyncHandlerFactory,
                requestContextFactory: _requestContextFactory,
                policyRegistry: _policyRegistry,
                mapperRegistry: _messageMapperRegistry,
                outBox: _outbox,
                asyncOutbox: _asyncOutbox,
                messageProducer: _messagingGateway,
                asyncMessageProducer: _asyncMessagingGateway,
                outboxTimeout: _outboxWriteTimeout,
                featureSwitchRegistry: _featureSwitchRegistry
            );
        }
        else if (_useRequestReplyQueues)
        {
             return new CommandProcessor(
                subscriberRegistry: _registry,
                handlerFactory: _handlerFactory,
                requestContextFactory: _requestContextFactory,
                policyRegistry: _policyRegistry,
                mapperRegistry: _messageMapperRegistry,
                messageProducer: _messagingGateway,
                responseChannelFactory: _responseChannelFactory 
                );
        }
`
we end up with the Bottom Command Process which does not initiate any Async Handler Factories and as such we fail on being able to Handle with "Invalid Operation : No Async Handler Factory Defined." (CommandProcessor.cs Line 438)

If this the intended Behaviour? I am not 100% certain of this terminology but I would have thought we want TaskQueues not RequestReplyQueues as we just want commands to be sent and dont require an ACK from the Downstream Consumers, but I fear I may miss understand Brighter TaskQueues vs RequestRequestReply Queues

**Comment by preardon** [comment]
From what I see the Current logic is

IF we support Receiving and Sending => Request Reply Queues
IF we support Receiving but not Sending => No Task Queues
IF we dot not support Receiving but support Sending Sending => Task Queues
If we do neither => No Task Queues

but from what I Understand, I want to be able to send and Receives but I don't Want RequestReplyQueues

**Comment by preardon** [comment]
I've gone through a Few Iterations here


 `   
if (options.ChannelFactory is null)
            {
                
                taskQueuesBuilder = options.BrighterMessaging == null
                    ? messagingBuilder.NoTaskQueues()
                    : messagingBuilder.TaskQueues(new MessagingConfiguration(options.BrighterMessaging.OutBox,
                        options.BrighterMessaging.AsyncOutBox, options.BrighterMessaging.Producer,
                        options.BrighterMessaging.AsyncProducer, messageMapperRegistry));
            }
            else
            {
                if (options.BrighterMessaging == null)
                {
                    taskQueuesBuilder = messagingBuilder.NoTaskQueues();
                }
                else if (options.BrighterMessaging.OutBox != null || options.BrighterMessaging.AsyncOutBox != null)
                {
                    taskQueuesBuilder = messagingBuilder.TaskQueues(new MessagingConfiguration(options.BrighterMessaging.OutBox,
                        options.BrighterMessaging.AsyncOutBox, options.BrighterMessaging.Producer,
                        options.BrighterMessaging.AsyncProducer, messageMapperRegistry));
                }
                else
                {
                    taskQueuesBuilder = messagingBuilder.RequestReplyQueues(new MessagingConfiguration(options.BrighterMessaging.OutBox,
                        options.BrighterMessaging.Producer, messageMapperRegistry, responseChannelFactory: options.ChannelFactory));
                }
            }
`

Being one of The Latest ones as Request Reply Queues don't set the Outbox 

however I just ended up adding an Option to Brighter Messaging

**Comment by preardon** [comment]
I have Just added PR #1546

**Comment by preardon** [comment]
This fix has been merged in

**Comment by iancooper** [comment]
I think this works for now. I sense it smells a little, as though we might need a flag based enum that says 'turn on these features' as inferring has become too complex. One for post 9.0 to talk over witth @holytshirt
