### ISSUE TITLE
Support for RMQ Topic Exchanges?

### ISSUE THREAD

**Issue by eskitek** [BrighterCommand/Brighter#156]
Hi - I was wondering if there is a way to create a topic exchange in RMQ. By default, the RMQ Messaging Gateway creates a direct exchange. Looking through the code a bit, I can see that there is a property called "Type" in RMQMessagingGatewayConfigurationSection that appears to be relevant, but it doesn't seem to be used when an exchange is created/configured in MessageGatewayHelper. Thanks!

**Comment by iancooper** [comment]
Hmmm, we might nee to fix that. @eskitek Sorry for the late reply. It's worth using the Gitter chat room to get attentions if you raise an issue: https://gitter.im/iancooper/Paramore

**Comment by ianbattersby** [comment]
Does look like Type configuration attribute gets ignored: https://github.com/iancooper/Paramore/blob/3d3c604d9ad9aeb1a44accbff00fc5399c5a7871/Brighter/paramore.brighter.commandprocessor.messaginggateway.rmq/MessageGatewayHelper.cs#L42

**Comment by iancooper** [comment]
Fixed this one, because the strategy of waiting on first-timers should not really be applied to bugs i.e. help wanted and bug are pretty much incompatible labels. We should make sure that bugs are not flagged as help-wanted
