### ISSUE TITLE
EntityFramework Outbox

### ISSUE THREAD

**Issue by nesbo** [BrighterCommand/Brighter#1573]
Hey all lovely people,

just using Brighter with ASB and love the Outbox, except that I'd like my command processing to be atomic and wrap my EF stuff together with Posting new command (to the Outbox obv) inside single db transaction. MSSql Outbox is not using ef contexts, therefore not helping much on this topic.

Do we have any thoughts on this, discussions open or concerns?

Cheers!

**Comment by preardon** [comment]
Hi @nesbo 

In v9 we broke the connection for Outbox to have a ConnectionFactory, my thoughts for this was that you can implement your own Connection Factory, Inject your EF context and use the DB for that to provide the DB Connection.  I will look to get an example of this and post it here.

**Comment by preardon** [comment]
I still have to Test, however this is looking good

`
public class MsSqlOutboxEFConnectionFactory : IMsSqlOutboxConnectionFactory
    {
        private GrettingsDbContext _context;
        
        public MsSqlOutboxEFConnectionFactory(GrettingsDbContext context)
        {
            _context = context;
        }
        public DbConnection GetConnection()
        {
            return _context.Database.GetDbConnection();
        }

        public async Task<DbConnection> GetConnectionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            var tcs = new TaskCompletionSource<DbConnection>(TaskCreationOptions.RunContinuationsAsynchronously);

            tcs.SetResult(GetConnection());

            return await tcs.Task;
        }
    }
`

**Comment by iancooper** [comment]
@nesbo Does this work as a solution?

**Comment by preardon** [comment]
@iancooper I've just had a little bit of a look into implementing it and found a small hitch, we need the DbContext to be DI injected and the way the outbox is currently setup it does not appear to support this (As we Create a factory and pass it to Configuration) I will have a bit more of a think and come up with a solution but might require a little bit of a change to the initialisation of Outbox

**Comment by preardon** [comment]
@iancooper @holytshirt Do we have the ability to include our current MsSql outbox implementation in a Transactions started from Application code. I can't currently see how this would work, I've been going around with how to do this at the Minute, I've made some small changes around the the Service Collection Extensions, and Command Processor Builder which allows a Nice easy injection of and use of the EF Database connection, However its looking more and more like we need some larger changes to MsSql outbox itself

**Comment by preardon** [comment]
@nesbo There is a Solution for this in PR #1601 
src/Paramore.Brighter.Inbox.MsSql/ConnectionFactories/MsSqlInboxManagedIdentityConnectionFactory.cs

**Comment by holytshirt** [comment]
@sdcondon this will be of interest to you

**Comment by preardon** [comment]
This is now in master, please note if you want to use this you need to have your Command Processor as a Scoped service (have a look at my ASB Sample web app), this is a basic working example

**Comment by iancooper** [comment]
All going to close this issue, please raise new ones for further outstanding items
