### ISSUE TITLE
Service activator - RejectMessageAction

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1578]
At this minute the only way for Command Handler code to talk to the message pump is by throwing a DeferMessageAction which will retry the message and eventually add it to the Dead Letter Queue (If Applicable)

I would like a RejectMessageAction which instructs the Message Pump to Dead Letter the Message for when the issue is not due to a Transient issue.

I am currently wondering weather this is an Anti Pattern (do we want validation issues in the DLQ, perhaps Best Practices is to store them elsewhere?)

@iancooper If you are happy with this I am happy to put it into the Pump

**Comment by iancooper** [comment]
So, technically:

- Message you cannot translate: Invalid Message Queue. 
- Message you cannot deliver: Dead Letter Queue
- Application Error: Log them as any application error. We will ack any message that throws an exception i.e. you reject. If you want a copy, use an Inbox

So we prefer not to to let you use the DLQ.

However, I know some folks do want an error queue, and there is always a question if having advised about best practice, do we still let you do that or do we just say no. 

Open to the discussion of the definition of an error queue. Whilst I may think it's wrong, it might be alright as an option. I think it would mean that we would have to forward all messages where we ack following an unhandled exception on it if you set one up, and that means you would not need a specific exception to force that behavior.

Happy to chat at the next Zoom call.

**Comment by preardon** [comment]
@iancooper Thanks for the Clarification, I suppose I was treating the DLQ as a Standard "Could not Process" queue, most of the cases in my head were things like Validation Failures which I suppose you could say that should not happen, but this would fall under Application Error Umbrella.

So while I  can see why people would reach for this first, it is then Treating the DLQ as a generic Error Queue. I know when I first looked at the Pump I did originally wonder why we were not retrying on any failure, however on further use I can see why we do not want to retry on all failures and as such only retry on Defer Action as it forces the control into the Command Handler.
