### ISSUE TITLE
Async Outbox Sweeper

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1582]
At the moment Brighter only has synchronous Outbox Sweeper

I would also like to be able to use it with Async Outboxes

Low Priority, I can look to get this out after v9

**Comment by preardon** [comment]
Also, just a thought, is there any reason we wouldn't just make this Static (if we are just passing in All the Deps anyway)

**Comment by iancooper** [comment]
So the Outbox Sweeper is intended to run on a dedicated background thread. Making it async would probably make it slower, because there would be nothing else to schedule against it. Still, I don't mind you doing an async version, I'm just not sure of the value. We could make it static rather than an instance.

**Comment by preardon** [comment]
@iancooper Had some time this morning so I thought I'de get this one knocked off

**Comment by preardon** [comment]
It looks like we have some Unit Tests failing on master (for MsSql Outbox)

**Comment by preardon** [comment]
@iancooper Is it correct that if there is no message found in the outbox we want it to return a MT_None Messages instead of a null. I understand that in the Command Pump we want this, however its fed from a queue not an outbox?

**Comment by preardon** [comment]
I've found some Bugs, I will get a fix in for these

**Comment by iancooper** [comment]
I'll need to take a look. Let me stick my current work on a PR, as there is a little bit of change to OutboxSweeper

**Comment by preardon** [comment]
Not a problem I'll rebase onto yours

**Comment by iancooper** [comment]
See this: https://github.com/BrighterCommand/Brighter/pull/1708

I need to test the MySql stuff before it gets out of draft.

**Comment by preardon** [comment]
I'll can have a fix for the MySql Sweeper in 30 minutes if you haven't done it already

**Comment by preardon** [comment]
@iancooper I haven't rebased on your branch yet, would you like me to?

**Comment by iancooper** [comment]
May be easier for you to go first and me to rebase

**Comment by iancooper** [comment]
If you are done, we could just merge you in?

**Comment by preardon** [comment]
Looks like I have a small change to make to InMemory Outbox (its never defined as Aysnc however some of the test call sweepAsync), so I'll have a look at making InMemory an Async Outbox viewer (Even though there is really no point)

Or would you prefer that In Memory to fail if you try to Async?

**Comment by iancooper** [comment]
Nah, just use the TaskCompletionSource pattern to return a task on the async api implementation for the in memory message box.

**Comment by iancooper** [comment]
I'll wait for you to merge, and then merge your changes from master. I was about to test MySql in my example, so I'll just hit bugs you have fixed, and might as well wait for your changes first.

**Comment by preardon** [comment]
there is also a small change you can make to your code with mine now that the sweeper is static as well, so you don't have to instantiate an instance

**Comment by iancooper** [comment]
Cool, that may make that code easier. Let me know when we are merged.

**Comment by preardon** [comment]
There is one final test that appears to be hanging (on Async Sweep) but I have pushed lets see how the tests run in CI

**Comment by iancooper** [comment]
Cool. I won't get to this again until next week probably, so don't kill yourself.

**Comment by preardon** [comment]
@iancooper Should be good now, the aws CI doesn't work due to missing Creds apparently, issue was with Task Completion Source in Fake Command Processor

**Comment by iancooper** [comment]
Did a merge, going to close this issue
