### ISSUE TITLE
MsSQL Outbox Error when calling OutstandingMessages - System.InvalidCastException: The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1583]
I am vaguely sure this was working, and I can not yet see why it is doing this, however at the minute I am currently getting

System.InvalidCastException: The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects.
   at Microsoft.Data.SqlClient.SqlParameterCollection.ValidateType(Object value)
   at Microsoft.Data.SqlClient.SqlParameterCollection.AddRange(Array values)
   at Paramore.Brighter.Outbox.MsSql.MsSqlOutbox.CreatePagedOutstandingCommand(DbCommand command, Double milliSecondsSinceAdded, Int32 pageSize, Int32 pageNumber)
   at Paramore.Brighter.Outbox.MsSql.MsSqlOutbox.OutstandingMessages(Double millSecondsSinceSent, Int32 pageSize, Int32 pageNumber, Dictionary`2 args)
   at Paramore.Brighter.OutboxSweeper.Sweep()
   
I find it confusing that this would be an issue in the Brighter as I would imagine that there are tests and someone would have brought it up. 

If anyone has any ideas as to how my configuration could have caused this then that would be much appreciated, otherwise I am going to keep looking and post an answer here when I have one

**Comment by preardon** [comment]
I've found something that fixes this, but Its on the Brighter side,

If we change the Reference in MsSqlOutbox to Microsoft.Data.SqlClient from System.Data.SqlClient, Then it Magically starts working, I'm not Overly sure Why this works, or how it would work if we were to pass a Null Value into the Parameters.

@iancooper Given that Microsoft have been looking at replacing System.Data.SqlClient with Microsoft.Data.SqlClient, what are your thoughts on me updating these References?

**Comment by holytshirt** [comment]
I would use ` Microsoft.Data.SqlClient`. ` System.Data.SqlClient` is only for legacy support.

**Comment by preardon** [comment]
@holytshirt that was my understanding as well. 

I have played with this a bit this afternoon and it looks to work fine so far, didn't quite get to the ci tests in the pipeline due to the artifacts post failure.

I've been spending some time in one around outbox today, will have some questions/suggestions but can obviously wait until v9.x

**Comment by iancooper** [comment]
Can't see why we shouldn't switch over. Likely anyone using the lib has moved their dependency too, or will need to anyway.

**Comment by iancooper** [comment]
Worth noting that this probably applies to Inbox and transport too, and we should upgrade all of them

**Comment by preardon** [comment]
> Worth noting that this probably applies to Inbox and transport too, and we should upgrade all of them

Already have upgraded inbox, I'll get transport done and in the PR in the next 39 mins

**Comment by iancooper** [comment]
That's very precise...

**Comment by preardon** [comment]
@iancooper I am now seeing this in a few more place, I think I'm going to have to go through it and Change all DbParameters & Connections to SqlParameters and SqlConnections.

I can get this done this afternoon

Still perplexes me as to why this as all of a sudden become an issue
