### ISSUE TITLE
AwsSqs - Option to read Sqs message with Sns metadata

### ISSUE THREAD

**Issue by honkuan86** [BrighterCommand/Brighter#1597]
**Is your feature request related to a problem? Please describe.**
For the ServiceActivator and a Sqs message consumer to read and dispatch message correctly, we need to enable Raw Message Delivery in Sns subscription. This request is to add an option like "**RawMessageDeliveryDisabled**", so that the SqsMessageCreator knows it needs to strip off the Sns metadata when reading a message body.

**Describe the solution you'd like**
Add an new option like "**RawMessageDeliveryDisabled**" in SqsConsumer passing down from SqsSubscription, so user can configure during setup.

**Comment by honkuan86** [comment]
@holytshirt , @iancooper , I can pick this up if this makes sense.

**Comment by iancooper** [comment]
@honkuan86 Feel free to have a stab at this. Generally, I would agree, add an option, probably just call it RawMessageDelivery and default it to true over the double negative. 

You then need to look at both how to obtain our message header data from the message body now, as well as find the body. I would suggest we would like to see some sort of strategy around this i.e. a SQSMessageCreatorFactory that gives you either an SQSRawMessageCreator (today's code) or an SQSInlineMessageCreator that inlines the SNS header info into the body and picks up values from there.

Then the calling code can pick the relevant *creator from the subscription flag.

This also allows you to write tests for the different strategies.

**Comment by iancooper** [comment]
@honkuan86 Did you make any progress with this? Do you need more help? We could set up a Zoom call if that would help.

**Comment by honkuan86** [comment]
@iancooper , I haven't got chance to get on the code yet, planning to work on this in this weekend.

**Comment by honkuan86** [comment]
Closing this as the feature has been merged.
