### ISSUE TITLE
CommandProcessor doesn't support Request/Reply and async handlers in the same configuration

### ISSUE THREAD

**Issue by DevJonny** [BrighterCommand/Brighter#1634]
### Describe the bug
The [CommandProcessor.cs](https://github.com/BrighterCommand/Brighter/blob/a3ea14247e00b1b7c52d37e298f5be580a006504/src/Paramore.Brighter/CommandProcessorBuilder.cs#L254) constructor for Request/Reply doesn't allow for adding an `IAmAHandlerFactoryAsync.cs` instance.

Using either the `CommandProcessor` or the `CommandProcessorBuilder` you are unable to set the `IAmAHandlerFactoryAsync` and a `responseChannelFactory` in the same constructor.

I'm not sure if this is by design, or not. If it is by design, what is the recommended approach to supporting both Request/Reply and Async Handlers in the same project other than having two separate CommandProcessors.

I'm happy to pick this up if it is not by design.

**Comment by iancooper** [comment]
@DevJonny Yeah, it's not by design. Things are a little better on this in 9, but it still needs work to be right. We have clarified some names, and intent there around what constructor you should use, but adding request-response on top is still not right.

Have a look if you can.

**Comment by DevJonny** [comment]
Great, thanks for clarifying @iancooper I’ll definitely take a look and hopefully get a PR sorted.
