### ISSUE TITLE
Dockerhub Community Application

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#1693]
Dockerhub has updated its licensing requirements. We do have an org on Dockerhub, which would allow us to push to dockerhub, although  I don't believe that we actively use it since we dropped AppVeyor. We will pull containers during our GA build though.

I have completed a Dockerhub community OSS application for Brighter, so that we don't hit any service issues.

**Comment by holytshirt** [comment]
Dockerhub monitors changes to our docker file for rabbitmq + delay plugin https://github.com/BrighterCommand/Brighter/blob/master/Docker/RabbitMQ/Dockerfile and will build a new one container. We then used that when we started up a rabbitmq container for tests https://github.com/BrighterCommand/Brighter/blob/master/docker-compose-rmq.yaml#L5

**Comment by iancooper** [comment]
@holytshirt Docker have accepted us and we are no longer subject to their pull rate limits.
