### ISSUE TITLE
CommandProcess.Call() breaking due to Subscription not being RmqSubscription

### ISSUE THREAD

**Issue by DevJonny** [BrighterCommand/Brighter#1699]
### Describe the bug
When CommandProcessor.Call is invoked a generic `Subscription` is created and passed to the `ChannelFactory.CreateChannel()`. The [ChannelFactory](https://github.com/BrighterCommand/Brighter/blob/e605ef111cca1c15e6a053cc51bec3087fa2a63c/src/Paramore.Brighter.MessagingGateway.RMQ/ChannelFactory.cs#L53) enforces the type of the Subscription to match the type of messaging gateway.  

### To Reproduce
This can be reproduced using the `RMQRequestReplyExample` project in Samples.

### Exceptions (if any)
```
Unhandled exception. Paramore.Brighter.ConfigurationException: We expect an RmqSubscription or RmqSubscription<T> as a parameter
   at Paramore.Brighter.MessagingGateway.RMQ.ChannelFactory.CreateChannel(Subscription subscription) in D:\dev\huddle\Brighter\src\Paramore.Brighter.MessagingGateway.RMQ\ChannelFactory.cs:line 57
   at Paramore.Brighter.CommandProcessor.Call[T,TResponse](T request, Int32 timeOutInMilliseconds) in D:\dev\huddle\Brighter\src\Paramore.Brighter\CommandProcessor.cs:line 724
   at GreetingsSender.Program.Main(String[] args) in D:\dev\huddle\Brighter\samples\RMQRequestReplyExamples\GreetingsClient\Program.cs:line 75
```

**Comment by DevJonny** [comment]
@iancooper was `.Call()` designed only for RMQ or all Messaging Gateways. Just working through ways of fixing this and the check for the right type of subscription is trashing most of my ideas.

One I did have was having a separate method on the `IAmAChannelFactory` that would allow for a simpler set of values to be passed to create the temporary queues, but I'm not sure that will work for all Messaging Gateways, but I'm most familiar with RMQ and a much lesser degree SNS/SQS. I'll keep having a play around and see what else I can come up with.

**Comment by iancooper** [comment]
@DevJonny It ought to work for things like SNS+SQS too, but I can't recall now how far I got beyond making RMQ work TBH We should not close out that option. The Channel Factory idea does have some merits
