### ISSUE TITLE
When a TransactionConnectionProvider and Calling POST this will fail

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1757]
### Describe the bug
When Calling Post it then calls Deposit and then Clear

When a TransactionConnectionProvider is provider added Deposit defined it automatically uses an open transaction if there is one where as Clear does not, so when a Transaction is open we can Deposit Post but Cannot clear as it is not yet committed

@iancooper  I will look to fix this so that if we call Post / PostAysnc it does not attempt to use any open transactions

**Comment by iancooper** [comment]
@preardon thanks, closed
