### ISSUE TITLE
When calling ClearOutbox on a MsSql outbox, if it can't find the message it will still try to send

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1758]
When Calling Clear the Outbox, if MsSQL is configured and it cannot find the message it will return new Message() instead of null

**Comment by iancooper** [comment]
I know in some places we use the pattern of returning an MT_EMPTY message over a null message i.e. null object pattern. Is this the intent here?

**Comment by iancooper** [comment]
@preardon yeah, I guess if you pass me a missing Guid there is no way to "handle" that error, and in principle something went badly wrong.

**Comment by iancooper** [comment]
@preardon Agreed. And having been a C++ programmer from the COM error, I'm not a fan of forcing you to check a function cal for ok/err every time, if the non-exceptional case is success

**Comment by preardon** [comment]
@iancooper this can now be closed
