### ISSUE TITLE
[Feature] DynamoDb Transaction Provider

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#1776]
**Problem**
It is not possible to participate in a DynamoDb transaction when writing to the Outbox

**Solution**
We should utilize the new transaction provider pattern to make it possible to use a DynamoDb transaction to ensure that the Outbox writes occur in the same transaction as the entity writes.

**Describe alternatives you've considered**
- Use single table approaches to the Outbox. This is hard for us to provide help with because we don't know you keys, but we should look at this alternative at the same time, to see if we can support it as an alternative
- Use the transaction log pattern. We should do this, but it would be out-of-process and is raised as a separate piece of work

**Comment by Thijmen** [comment]
@iancooper I believe this can be closed?
