### ISSUE TITLE
Check if only one handler is register for `Send` command

### ISSUE THREAD

**Issue by michalczukm** [BrighterCommand/Brighter#186]
At the moment exactly one command handler can be registered for one command processed by `CommandProcessor` by `Send` both sync and async. [It can be found here](https://github.com/iancooper/Paramore/blob/master/Brighter/paramore.brighter.commandprocessor/CommandProcessor.cs#L755)

But during configuration you can register multiple handlers to it.
It will be undetected untill `CommandProcessor` handles such a command, then `ArgumentException` is thrown.

The exception/error could be thrown during configuration to avoid such a unpleasant surprises at runtime.

**Comment by michalczukm** [comment]
@iancooper the issue we twitted today.
You think also `ArgumentException` should be thrown when a violation is found? Or something more descriptive?

**Comment by iancooper** [comment]
We have our own custom ConfigurationException, so we can raise one of those

**Comment by michalczukm** [comment]
I just took on this issue, It should be handled in `CommandProcessorBuilder` or somewhere else?
Maybe `CommandProcessorBuilder` is not the only place?

**Comment by iancooper** [comment]
We may leave it for now as it doesn't seem to be a huge issue in usage. Feel free to re-open if you want to deal with it and have a plan :-)

**Comment by michalczukm** [comment]
Almost forgot about it, nightly board cleaning as I see ;)
