### ISSUE TITLE
[Feature Request] Support multiple topics/keys in publications

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#1890]
**Is your feature request related to a problem? Please describe.**
Raised by @honkuan86 and @pieperu on separate transports. Whilst out model under RMQ was to send to the topic identified in the header, because we always created the required infrastructure, the move to publications and support for creating the required infrastructure has created the issue that most publications only support one topic/key forcing the creation of  multiple producers etc.

**Describe the solution you'd like**
It should be possible to pass an array of publications to a producerfactory when creating a producer and have the relevant action: create, validate or assume enacted for each of them in turn. Sending code should always use the topic from the message header, and so should not need to be aware which publication. The producer should not need to know publication details that relate to infra. If the producer needs to use different publication characteristics for different channels then the producer code for that transport will have to track matching the appropriate characteristics at the time of send. We should avoid this complication if possible.

**Describe alternatives you've considered**
The current alternative is multiple command processors with their own producer.

**Comment by iancooper** [comment]
@pieperu offered to look at this

**Comment by iancooper** [comment]
@pieperu I'm going to take a first stab at this, as it may involve a breaking change, so best to get it into v9. I'll notify when the PR is up to discuss

**Comment by iancooper** [comment]
My first thought on this was  a bust. I looked at Kafka and tried to create an collection of Confluent Kafka Producers within it. That gets nasty because our producer wraps their producers. i think instead the answer is to have the factory return multiple producers, and have the lookup in CommandProcessor to a dictionary via topic. That feels less inasive.

I'll raise a PR when I get a transport right, so others can comment

**Comment by iancooper** [comment]
OK, I now have an IAmAProducerRegistry, which feels right as it fixes other issues around sync and async producer dependencies. Will raise a PR (draft for now).

**Comment by pieperu** [comment]
@iancooper apologies I’m late to the party and happy new year! I’ve been away since around 10th December. Will check out the PR out of interest and hope I can contribute more in 2022.

**Comment by iancooper** [comment]
@pieperu Definitely have a look, would appreciate the feedback
