### ISSUE TITLE
[Feature] Support for MQTT protocol

### ISSUE THREAD

**Issue by timvw74** [BrighterCommand/Brighter#1896]
Brighter doesn't currently support the MQTT protocol.

It would be useful to be able to produce and consume from MQTT.

MQTT pushes from the server, so we may need to do something similar to the RMQ support.

**Comment by timvw74** [comment]
I have started working on a solution for this.

**Comment by iancooper** [comment]
Thanks @timvw74

**Comment by iancooper** [comment]
@timvw74 Any progress on this?

**Comment by iancooper** [comment]
Move this to: https://github.com/petabridge/TurboMqtt

**Comment by iancooper** [comment]
Going to close this as @timvw74 has made a contribution. We can raise some new issues to update the library version
