### ISSUE TITLE
[Feature Request] Dapper Support for Outbox

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#1937]
**Is your feature request related to a problem? Please describe.**
To use the Outbox effectively you need to ensure that any transaction that is used to write entities to the store, is also used to write the message to the Outbox. To do this, we need to provide the transaction to the Outbox code by implementing the relevant interfaces for the persistence library. We have an "out of the box" solution for EF Core, adding Dapper would cover the two most common dev libraries for persistence in .NET today.

**Describe the solution you'd like**
Developers using Dapper have a supported model for using the Outbox where persisting entities

**Describe alternatives you've considered**
Allow the messages to persist to the Outbox on a separate transaction - this weakens the guarantees of the Outbox

**Comment by IlSocio** [comment]
hello @iancooper 
maybe I got it wrong, so please, feel free to correct me.

To my knowledge dapper is nothing more than a very nice set of extensions methods over the standard ado.net connection, so, I believe there isn't anything in particular to do to support Dapper.

This should be already present within the MsSql adapter.

**Comment by preardon** [comment]
@IlSocio isn't Dapper an ORM the same as Entity Framework core we have packages for EF for SQL server which allows the outbox to take part in the applications database transactions if you have a look at the MsSql.EntityFrameworkCore pacakge as a reference

**Comment by IlSocio** [comment]
Actually no, Dapper is a "lite-ORM", unlike EF, Dapper doesn't provide a unit-of-work / DbContext, but more important, it doesn't encapsulates the connection / transaction like the DbContext.

Dapper only provides some extensions methods over the existing ADO Net IDbConnection interface.
eg: 
`public static int Execute(this IDbConnection cnn, string sql, object param = null, IDbTransaction transaction = null, int? commandTimeout = null, CommandType? commandType = null)`
Meaning that the life-cycle of the connection / transaction, is up to the developer, as in "pure" ADO Net.

For this reason the existing MsSql adapter should already work with Dapper.

**Comment by iancooper** [comment]
I’m exploring it now. 

It’s a placeholder. I’m writing a sample, because we want to make it easy for folks who use that approach. As part of that sample if I want to add anything, this gives me an issue to track that against for a separate PR.

Dapper is a set of extension methods to IDbConnection, so they key issue is sharing the same connection as Dapper is using with the Outbox.

>

**Comment by iancooper** [comment]
Done. Please look at the samples. Feedback is welcome
