### ISSUE TITLE
No tags on NuGet packages

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#197]
We don't support any tags on our NuGet packages. That will make us hard to find. Looking at others tags, those that may be appopriate include:

RabbitMQ, Messaging, AMQP, ServiceBus, PubSub, Publish, Subscribe, Queue, Topic, Relay, Service, Bus, CQRS, Command Dispatcher, Command Processor, Command, Event, Broker, Task Queue, Work Queue, Retry, Circuit Breaker, Availability

**Comment by jplebre** [comment]
I'll give this a go

**Comment by iancooper** [comment]
@jplebre Did we get anywhere wit this. I forget. It might be worth checking over this on the new packaging with @holytshirt to see if we have support for tags there

**Comment by iancooper** [comment]
We now have these
