### ISSUE TITLE
Data Type for Connection cannot be found in the component When Ports are in different Assembly

### ISSUE THREAD

**Issue by gazlu** [BrighterCommand/Brighter#204]
When we keep port in different assembly than the ServiceHost the ServiceActivation does not resolve the data type, I think following trick would help to resolve this.

This issue further leads to not invoking the respective CommandHandler

`Type dataType = Type.GetType(typeName);
 if (dataType != null)
     return dataType;`

**Comment by iancooper** [comment]
Are you using a full name for the type i.e. with assembly name? We use this approach all the time, and it works for us. Any chance you could check

**Comment by gazlu** [comment]
Sure, I will check
