### ISSUE TITLE
[Bug] Inbox table is not getting populated when using EntityFrameworkCore-WebApi example

### ISSUE THREAD

**Issue by omelianlevkovych** [BrighterCommand/Brighter#2052]
### Describe the bug
The consumer Inbox table (Salutations database) is empty after handling the message broker message, even though the entity table (Salutations table) is getting populated.  
I assume that _from the box_ behavior is when getting the new entity instance in my consumer database I should also have new Inbox row in the database. Please correct me if I am wrong here.

**It works** when the **UseInboxAsync** attribute is used for the consumer handler.
### To Reproduce
* I am using Production launch settings `dotnet run --launch-profile Production` for the both GreetingsWeb and SalutationsAnalytics projects
* Therefore I have spinned MySQL database instance via docker-compose (also with the phpmyadmin page for it and Rabbit Message Queue as a message broker)

Salutations table:
![image](https://user-images.githubusercontent.com/22483733/160685704-2d3bf1c8-5579-43de-aaad-a767a33f5e87.png)
Inbox table:
![image](https://user-images.githubusercontent.com/22483733/160685841-10c6b97e-670a-436d-9b9f-92f4a91efdbd.png)

### Further technical details
- Latest Brighter version 9.1.2
- Windows 10 OS with docker for RMQ, MySQL & phpmyadmin
- `> dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.300-preview.22154.4
 Commit:    1eb22793b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\

.NET SDKs installed:
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]
  6.0.300-preview.22154.4 [C:\Program Files\dotnet\sdk]m Files\dotnet\sdk\6.0.300-preview.22154.4\
```

**Comment by preardon** [comment]
Sorry its taken me so long to response, I'll see if I can look at this over the next few days, I've yet to play with inbox as yet

**Comment by iancooper** [comment]
@preardon @IlSocio Yeah, I spotted this bug as well when working with @omelianlevkovych. It looks as though the global inbox has broken, whereas the explicit inbox still works. That suggests a problem with the pipeline registration of global inbox.

Workaround is to use the attribute on the handler for now.

**Comment by iancooper** [comment]
@preardon @IlSocio I'll pick this one up.

**Comment by iancooper** [comment]
Needs to check if the InboxConfiguration as part of ServiceActivator configuration fixes this
