### ISSUE TITLE
The current version cannot work with the latest Polly library.

### ISSUE THREAD

**Issue by vendre21** [BrighterCommand/Brighter#214]
The current version cannot work with the latest Polly library.
When I use the latest Polly library I will get the following exception when I try to create a new instance of RmqMessageProducer.
 
Could not load type 'Polly.ContextualPolicy' from assembly 'Polly, Version=5.0.6.0, Culture=neutral, PublicKeyToken=null'.

**Comment by holytshirt** [comment]
Thank you, I'll have a look over the weekend.

From: vendre21
Sent: 17 March 2017 13:16
To: BrighterCommand/Paramore.Brighter
Cc: Subscribed
Subject: [BrighterCommand/Paramore.Brighter] The current version cannot workwith the latest Polly library. (#214)

The current version cannot work with the latest Polly library.
When I use the latest Polly library I will get the following exception when I try to create a new instance of RmqMessageProducer.
Could not load type 'Polly.ContextualPolicy' from assembly 'Polly, Version=5.0.6.0, Culture=neutral, PublicKeyToken=null'.

**Comment by dstockhammer** [comment]
Fyi, #217 includes a Polly upgrade to version 5.0.6
