### ISSUE TITLE
Appveyor link to nuget feed on release notes out of date? 

### ISSUE THREAD

**Issue by scozzard** [BrighterCommand/Brighter#215]
Just an FYI really - I noticed the appveyor link (nuget feed for the last good master build) on the release notes is returning a 404.

I.e., the release notes:
https://github.com/BrighterCommand/Brighter/blob/master/release_notes.md

suggests the nuget feed for the last good build on master is:
https://ci.appveyor.com/nuget/paramore-gnrfp84lbfd3

Should this be updated?
Scott

**Comment by iancooper** [comment]
We will update as it has changed

**Comment by iancooper** [comment]
Fixed
