### ISSUE TITLE
Support VS 2017 .csproj project format

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#216]
We want to embrace the VS2017 project format, as project.json has been discontinued. We could run the wizard to convert over, but afterwards we would want to 'clean' any auto-generated build file to remove ay cruft.

See the discussion here: http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/

Current blockers:

- We use NUnit for tests (having converted over from MSpec). NUnit does not currently have a VS2017 compatible adapter: https://github.com/nunit/nunit3-vs-adapter/issues/305
- We don't want to switch to XUnit, because we used Setup and Teardown to convert our MSpec tests, but would have to now fold these into the tests themselves. This is a lot of work, and may not be worth it if NUnit fixes there issues soon
- We have customers still tied to VS2015. Their possible workaround is to use VS Code.

**Comment by dstockhammer** [comment]
I had a stab at xunit to see how difficult the switch really is. As it turns out, it wasn't difficult at all. There some other problems that need to be resolved though.
See #217

**Comment by iancooper** [comment]
Closed by https://github.com/BrighterCommand/Brighter/pull/217
