### ISSUE TITLE
[Bug] When using UseExternalBus extension on AWS SQS messaging gateway, it will throw "Missing SNS topic: <topic-name>" exception

### ISSUE THREAD

**Issue by iqbal-ideagen** [BrighterCommand/Brighter#2184]
### Describe the bug
When trying to add a topic property in SnsPublication object to UseExternalBus extension and run the code, it will immediately throw the `Missing SNS topic: <topic-name>` exception.

### To Reproduce

1. Use the AWSTaskQueue sample project and go to GreetingsPumper project specifically.
2. Open the Program.cs and make necessary changes to profileName and region
![brighter](https://user-images.githubusercontent.com/44764307/178942934-d1651ff2-b731-4aa9-acc8-9a8ba318a428.PNG)
3. Run the project and it should throw the  `Missing SNS topic: <topic-name>` exception

### Further technical details
- Brighter version 9.1.3
- Windows 10
- `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
```

**Comment by iancooper** [comment]
Fix is out in 9.1.4 or later.
