### ISSUE TITLE
Project doesnt build when cloned

### ISSUE THREAD

**Issue by loneshark99** [BrighterCommand/Brighter#224]
Hi,

I tried to build the project locally and it doesnt open in Visual Studio 2015. Is there anything I need to do to get it built on my box? Please let me know.

Thanks,
loneshark99

**Comment by dstockhammer** [comment]
VS 2015 is no longer supported. You either need VS 2017 or VS Code. Unfortunately there's nothing we can do about that :(

**Comment by loneshark99** [comment]
Thanks for the quick reply. Will use 2017.
