### ISSUE TITLE
Is it possible to use Queue instead of Topic for certain messages in ASB?

### ISSUE THREAD

**Issue by Arik-Shapiro** [BrighterCommand/Brighter#2241]
I want to be able to use Queues for Commands and Topics for events.
Is it possible to control whether the library uses a queue for a certain messages or a topic?

Thanks.

**Comment by Jonny-Freemarket** [comment]
@Arik-Shapiro would you mind moving this to [Discussions](https://github.com/BrighterCommand/Brighter/discussions) as that is a better forum to discuss this, and then we can raise an issue from it if necessary.
