### ISSUE TITLE
SQL message store uses square brackets incorrectly

### ISSUE THREAD

**Issue by dstockhammer** [BrighterCommand/Brighter#229]
In `MsSqlMessageStore`: 

```csharp
var sql = string.Format("INSERT INTO [{0}] (MessageId, MessageType, Topic, Timestamp, HeaderBag, Body) VALUES (@MessageId, @MessageType, @Topic, @Timestamp, @HeaderBag, @Body)", _configuration.MessageStoreTableName);
```
This results in the following SQL query:
```sql
exec sp_executesql N'INSERT INTO [MySchema.MyTable] (MessageId, MessageType, Topic, Timestamp, HeaderBag, Body) VALUES (@MessageId, @MessageType, @Topic, @Timestamp, @HeaderBag, @Body)'
```

Notice how `[MySchema.MyTable]` is incorrect. I think it's not possible to add square brackets like that, as you don't know if the `.` (dot) was in fact intended as separator or should be escaped.
The same applies to read queries.

**Comment by holytshirt** [comment]
Fixed and pushed
Fixes available in version 7.0.139
