### ISSUE TITLE
TargetFrameworks (plural) or TargetFramework?

### ISSUE THREAD

**Issue by shanselman** [BrighterCommand/Brighter#231]
I ran a sample like this:

```
D:\github\Brighter\samples\HelloWorld>dotnet run
Unable to run your project
Your project targets multiple frameworks. Please specify which framework to run using '--framework'.

D:\github\Brighter\samples\HelloWorld>dotnet run --framework netcoreapp1.1
Hello Ian
```
But changed the csproj from TargetFramework**s** to TargetFramework and it was simpler.

Was this intentional? If not, I'm happy to PR fixes for the samples.

**Comment by iancooper** [comment]
Yes, this should be <TargetFramework> and we are assuming that this has happened on the auto-conversion. A PR would be great; I suspect there are one or two more in the samples.

Just FYI we still multi-target .netstandard1.5 and net452 for users with older nuget feeds, but we intend to drop net452 soon and target .netstandar1.4

Copying in @holytshirt  as he is our build guru
