### ISSUE TITLE
Fail to produce Kafka message with additional header which in GUID value when using MySQL outbox

### ISSUE THREAD

**Issue by siewchinglim** [BrighterCommand/Brighter#2369]
### Describe the bug
When trying to produce a message with enabled MySQL outbox, it fails to create the additional header that with GUID value.

### To Reproduce
I'm using the sample code from Brighter (KafkaTaskQueue) to reproduce the issue. 

1. Modify the following files to enable MySQL outbox and add two additional headers (with string and GUID values). 
Program.cs in GreetingsSender:
![image](https://user-images.githubusercontent.com/23093177/202106145-2012244a-6b68-4a99-a9e0-19fcdf7cd213.png)

      GreetingEventMessageMapper.cs in Greetings:
      ![image](https://user-images.githubusercontent.com/23093177/202105928-f13d26de-a748-4887-b3a4-cf4fa6bdf49d.png)

5. View the message in Kafka via Kafka UI and you can find that header2 is not inserted to the message's header.
![image](https://user-images.githubusercontent.com/23093177/202103747-0d731a7c-d728-443f-8747-5461fb2445f6.png)

We will close this issue if:
Able to insert additional header with GUID value to Kafka message's header.

### Further technical details
- Brighter version 9.3.3
- `dotnet --info`
`.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.402\

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  6.1.425 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]
  6.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info`
- The OS (Window)

**Comment by mishadowlsc** [comment]
Hi @iancooper, may I know is this a known bug? Any workaround for me to insert additional header with GUID value when using external outbox?

**Comment by iancooper** [comment]
I'll have to investigate, thanks for the repro.

**Comment by Thijmen** [comment]
The issue lies here; https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessagePublisher.cs#L61

As Guid is not a string or an int, it's not being added as a header. A quick solution would be to cast it to a string when putting it to the header bag, or the KafkaMessagePublisher should do some logic to make everything a string (other than ints).
