### ISSUE TITLE
[Feature] Outbox maintenance - Dedicated methods for outstanding

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#2370]
At the minute the way that external bus service keeps track of the remaining amount of messages in the outbox is

```csharp
if (OutBox != null)
{
    _outStandingCount = OutBox
        .OutstandingMessages(
            producer.MaxOutStandingCheckIntervalMilliSeconds,
            args:producer.OutBoxBag 
            )
        .Count();
    return;
}
```

this will retrieve all of the outstanding messages from the outbox and then do a count, if there is a significant amount of outstanding messages this will be quite a costly operation.  I would like add the following methods to the outbox interface

  - Get number of outstanding Messages
  - Get last message dispatch time

**Comment by preardon** [comment]
@iancooper thoughts?

I am adding some outbox management stuff to my Sweeper service and I feel these would be good for the outbox to support

**Comment by iancooper** [comment]
@preardon Sounds good. I am always in favor of features we add from the experience of operating at scale.

**Comment by preardon** [comment]
This has been compelted for Async
