### ISSUE TITLE
Span status incorrect for Send() and SendAsync()

### ISSUE THREAD

**Issue by easyfy-fredrik** [BrighterCommand/Brighter#2398]
### Describe the bug
When using the (very shiny!) OpenTelemetry instrumentation the span status (Error/OK) gets flipped for Send() and SendAsync() while being correct for Publish() and PublishAsync(). 
This is currently giving us false negatives for all command sends. 

### To Reproduce
```
using var span = tracer.StartActivity("test") {
  commandProcessor.Send(command);
  //Nothing went wrong but span.Status == ActivityStatusCode.Error 
}
```

### Further technical details
- Brighter version 9.3.3

Not sure how to write tests for telemetry, although not part of the api/port it's certainly something that has consequences in the outside world, maybe something like a process-specific TracerProvider/ActivitySource as described in this article could be helpful?
https://www.honeycomb.io/blog/monitoring-unit-tests-opentelemetry

Here's a PR with a suggested fix:
https://github.com/BrighterCommand/Brighter/pull/2397

**Comment by iancooper** [comment]
Fixed via #2397
