### ISSUE TITLE
Azure Service Bus - AMQP - Delayed 

### ISSUE THREAD

**Issue by JacobAtchley** [BrighterCommand/Brighter#240]
I was looking at Brighter to see if it supports Azure Service Bus. I was browsing the repository when I noticed it doesn't support delayed messages. 

https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessageProducer.cs

I've delayed messages in other projects using the following snippet. Where `message` is an `Amqp.Message` instance and `enqueueTime` is a`DateTime?` instance.
```
if (enqueueTime.HasValue)
{
    if (message.MessageAnnotations == null)
    {
    	message.MessageAnnotations = new MessageAnnotations();
    }

    message.MessageAnnotations.Map.Add(new Symbol("x-opt-scheduled-enqueue-time"), enqueueTime.Value);
}
```

**Comment by iancooper** [comment]
I know that @dstockhammer  was looking at our Azure support. I need to ping him to find out where he is with this. We do support delayed messages for retries, but we don't support raising a message with a specific delay as yet.

We are looking into this. It's probable we will try to find an x-platform solution, perhaps using a priority queue on platforms that don't directly support delayed messaging, to allow users to create delayed messages. One idea is to post a delayed message onto the Control Bus, which would then fire it at a Data Bus when the delay had elapsed.

But the feedback on Azure is useful.

**Comment by iancooper** [comment]
I'm going to close as great feedback. We accept PRs happily though. You might want to come chat on the Gitter channel if you wanted to think about adding this kind of functionality.

https://gitter.im/iancooper/Paramore

Please re-open if you are not happy and want us to respond here in more detail instead.
