### ISSUE TITLE
[Feature] Customization of Casing of Kafka Message's Header Names

### ISSUE THREAD

**Issue by siewchinglim** [BrighterCommand/Brighter#2402]
I would like to create a Kafka message with headers named with camel case. However, Brighter has fixed the header names in the following code. I would like to request a feature to provide flexibility for us to configure the casing of header names.

> namespace Paramore.Brighter.MessagingGateway.Kafka
{
    public class HeaderNames
    {
        /// <summary>
        /// The message type
        /// </summary>
        public const string MESSAGE_TYPE = "MessageType";
        /// <summary>
        /// The message identifier
        /// </summary>
        public const string MESSAGE_ID = "MessageId";
        /// <summary>
        /// The correlation id
        /// </summary>
        public const string CORRELATION_ID = "CorrelationId";
        /// <summary>
        /// The time that message was sent
        /// </summary>
        public const string TIMESTAMP = "TimeStamp";
        /// <summary>
        /// The topic
        /// </summary>
        public const string TOPIC = "Topic";
        /// <summary>
        /// The key used to partition this message
        /// </summary>
        public static string PARTITIONKEY = "PartitionKey";
        /// <summary>
        /// What is the offset into the partition of the message
        /// </summary>
        public static string PARTITION_OFFSET = "TopicPartitionOffset";
    }
}
`

**Comment by iancooper** [comment]
Hi @siewchinglim, those defaults work because we support multiple transports, but we could look at an option that would allow you to choose camel case for the headers

**Comment by Thijmen** [comment]
@iancooper a nice solution could be that users can provide their own header implementation, how would you feel about that?

**Comment by iancooper** [comment]
@Thijmen @siewchinglim So I suspect that we need to use our JsonSerialisationOptions to control how this works. Looking at other transports I can see that we use this to control how header serialisation occurs. I'll put something together on this

**Comment by iancooper** [comment]
@honkuan86 Go for it.

**Comment by honkuan86** [comment]
hi @iancooper, may I know when we can get this release ?

**Comment by iancooper** [comment]
We are just discussing it. Shortly in a pre-release, and then a bit later on a final, once all the current set of features are documented and ***@***.*** 1 Feb 2023, at 13:42, Yong Hon Kuan ***@***.***> wrote:﻿
hi @iancooper, may I know when we can get this release ?
