### ISSUE TITLE
Remove LibLog

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#242]
Since we switched to XUnit for testing we have hit issues with tests that check on log output. I suspect that this is because LibLog uses statics, which essentially mean that we have a 'shared fixture' and that is going to break with the use of threads running multiple tests that may all try to initialize and clear settings to the logger.

An answer may be to look at initialization for the test suite with XUnit (and tear down) to remove timing issues.

Usually any CI issue can be fixed by re-running but it can be aggravating on a PR not to know if a merge will build, because we had a failing test caused by a parallelism issue.

![image](https://user-images.githubusercontent.com/45537/27681295-aa074dfa-5cb6-11e7-9db2-8347a18dc70e.png)

**Comment by iancooper** [comment]
LibLog has now been deprecated: https://github.com/damianh/LibLog

"My recommend course of action for library developers is to use Microsoft.Extensions.Logging.Abstractions as it is now the defacto standard logging interface in the .NET ecosystem. For library developers that wish to continue to use LibLog or need to make adjustments for their needs should copy the code into their project (after all, that's just what LibLog did).

Thanks to all contributors and users for the support over the years.

Damian"

Given that we now use HostBuilder, we may as well move towards accepting the use of Microsoft ILogger

**Comment by iancooper** [comment]
We should not the comments in #1254

**Comment by iancooper** [comment]
We should also note #299

**Comment by iancooper** [comment]
When looking at replacement of LibLog, I believe that there are a number of related issues:

(1) We should consider where a framework 'logs'. It may be better for a framework to use TRACE and DEBUG to allow consumers of the framework to diagnose faults, but not log, as logging from the framework may be verbose and unhelpful for highlighting problems in production code. Under this model, any existing logging we have for Information, Debug, or Trace logging levels would be a DEBUG statement and Warn, Error and Fatal would be TRACE. We would recommend against deploying a DEBUG build and only deploy a TRACE build for production issues.

(2) Supporting your logging then becomes only an issue of the request logging handler, and we should look to advice on high performance logging: https://www.stevejgordon.co.uk/high-performance-logging-in-net-core

This prevents the need to us to 'inject' logging into Brighter, outside of the request logging handler, instead we would rely on System Diagnostics for fault finding: https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/tracing-and-instrumenting-applications Output to a text listener would be simple enough to document: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.textwritertracelistener?view=net-5.0

Overall, this switch, to separate runtime logging from tracing brighter would have significant benefits if we document it effectively. It also provides a solution to obfuscation as these logs would probably not be ones you simply dump out to your log aggregator.

**Comment by preardon** [comment]
@iancooper how in this one going? Still need a hand?

**Comment by iancooper** [comment]
@preardon This one is with @holytshirt right now.

Plan has changed to:
* Use MS ILogger
* Use the approach outlined here to create a global logger factory and initialize class level loggers from it in their constructor:https://docs.microsoft.com/en-us/archive/msdn-magazine/2016/april/essential-net-logging-with-net-core
* Make it possible to set this from your logger via our hostbuilder extensions.

So it's up to @holytshirt if he wants help on it.

**Comment by preardon** [comment]
@holytshirt happy to help if you want a hand. I am familiar with ILogger.

Let me know if I could be of use

**Comment by preardon** [comment]
@holytshirt How is this one going mate? I really would like to see this in v9 as it gives me personally a lot for free (Logging into App Insights for a start)

Is there anything I can do to help?

**Comment by holytshirt** [comment]
Hey Paul,

Still in progress, have just trying to get a beta release out.

If I can get anywhere by Wednesday I may have to hand the baton over to you?

**Comment by preardon** [comment]
@holytshirt sounds good mate, let me know 🙂

**Comment by preardon** [comment]
@holytshirt How did we go with this mate?

**Comment by holytshirt** [comment]
@preardon it was quite a lot of replacing, pull request ready for review. 
Do you need the extra stuff for structured logging?
