### ISSUE TITLE
Azure Service Bus Issues

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#243]
- @has-taiar I moved your issue here

Hi  @@iancooper,
I am starting on a new project and I am glad that I found Brighter, I am hoping to use Brighter with Asp.Net Core :(
I am happy to offer any help to get this to .NET Core, so that we can use it and the rest of the community can use it too :)

The first blocker I saw was that it relies on Azure Service Bus Nuget packages which is compiled for the full .Net Framework. There is a new .netStandard-compatiblible version of the ASB nuget here: https://github.com/Azure/azure-service-bus-dotnet

Is there any other dependency on the full .net framework?

**Comment by iancooper** [comment]
I suspect that you are looking at the old package, we have just updated NuGet to kill those, to avoid this kind of confusion.

The latest version uses AMQPLite and the REST API, because that was what was available at the time, but may do little more than build as we have not tested this one in anger since we went to .NET Core.

We are not wedded to the use of AMQPLite or the REST API but no .NET Standard library for ASB existed when we ported this. We would love to take this forward to those packages.

A PR would be very welcome, the Huddlers on the team are AWS and RMQ so this languishes a bit for lack of support from someone working in Azure.

Please do try to fix if you can.

**Comment by dstockhammer** [comment]
I'm actually working on a new version of the Azure Service Bus gateway, but there are a couple of issues I need to sort out.

Unrelated to that, I'm not sure how far away .NET Standard support is. The new .NET Standard version of the Azure Service Bus package you mentioned seems to be quite far away from RTM, since there are a number of basic features missing. So for now it looks like Azure Service Bus users are unfortunately stuck on the full framework.

**Comment by iancooper** [comment]
I have moved this issue back to up for grabs

**Comment by penderi** [comment]
Hello ! I was wondering what state this was in ? Is there a plan, a branch or some code? Or is it already covered by a contrib project and thus closed *hopeful face*. Hope all are well!

**Comment by iancooper** [comment]
@penderi No, it's in alpha. We need someone who deals with ASB to pick it up really, because the rest of the team are RMQ or AWS 

We should do beer soon!

**Comment by penderi** [comment]
I may know someone. Us. Just need to know plans (ie how to map to ASB concepts). Simple would be good (at least for now) as tight timescales but willingness to help. Beer. Hell yeah.

**Comment by penderi** [comment]
I *may* have something coded. I've gutted the Sqs Messaging Gateway and have an ASB version working the same way. Can you let me know if that's what you had envisaged ? And that you're happy with the SQS code?

**Comment by penderi** [comment]
AND BEERS DATES

**Comment by penderi** [comment]
Re:ASB. It seems the only tricky part is on the consumer - what to use for Reject and Requeue.
So I need to know the nature of Reject (and go easy I am primitive in AMQP). Does this reject on this consumer and leave for another (seems like Abandon of lock in ASB) or is this reject the message for processing and dead letter?

Requeue - there's a path that suggests reject the message and re-sending. THere's no similar for ASB as reject would Abandon (as above - leave for another or dead letter) and re-send. We don't want to complete either as that's nasty for the next send. It seems the best is - defer processing or abandon. i.e.. re-process at head of queue (abandon) or at an arbtirary point later. Not terrible I guess.
