### ISSUE TITLE
[Feature] ReplyTo message header in Kafka transport does not get populated when reply is requested

### ISSUE THREAD

**Issue by iqbal-ideagen** [BrighterCommand/Brighter#2456]
### Describe the bug
For Request-Reply pattern scenario, ReplyTo message header is used to inform Consumer about the replyTo Topic and respond after the message is consumed. However in Kafka messaging gateway, seems like it's not using the ReplyTo header

### To Reproduce
Repro project: https://github.com/iqbal-ideagen/Brighter/tree/kafka_reply_to_error

In Apache Kafka UI, noticed that the message is missing the replyTo header
[
![image](https://user-images.githubusercontent.com/44764307/210699081-da20dde5-fe8d-402a-80f1-020c45e78de2.png)
](url)

### Further technical details
- Brighter version 9.6.3
- Windows 10
- `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
```

**Comment by iancooper** [comment]
@iqbal-ideagen 

This is out via 9.4.0-beta.3

You will need to opt to allow pre-release in NuGet to pick it up. We will move to release at some point soon, when we are sure the current batch of changes are stable.

**Comment by honkuan86** [comment]
Hi @iancooper , may I know roughly when will the changes be release ?
