### ISSUE TITLE
Show how Brighter can be used within eShopContainers 

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#246]
eShopContainers uses MeditatR and a homegrown library for doing inter-process messaging over RMQ.

We could replace both of those items fairly easily, and show how Brighter can be used in a microservices scenario.

https://github.com/dotnet-architecture/eShopOnContainers

**Comment by Pothulapati** [comment]
@iancooper Are anyone working on this? I would like to take this.

**Comment by iancooper** [comment]
This seems to be abandoned. Going to park the issue and come back if anyone has time
