### ISSUE TITLE
[Feature] MS SQL Inbox and Outbox DDL NText is deprecated 

### ISSUE THREAD

**Issue by holytshirt** [BrighterCommand/Brighter#2476]
https://learn.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql
> The ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use [nvarchar(max)](https://learn.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver16), [varchar(max)](https://learn.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver16), and [varbinary(max)](https://learn.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-ver16) instead.

The DDL we provided for Inbox and Outbox uses NText to store body and header

Inbox
https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter.Inbox.MsSql/DDL%20Scripts/MSSQL/Inbox.sql
https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter.Inbox.MsSql/SqlInboxBuilder.cs#L38

OutBox
https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter.Outbox.MsSql/DDL_SCRIPTS/MSSQL/Outbox.sql
https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter.Outbox.MsSql/SqlOutboxBuilder.cs

**Comment by iancooper** [comment]
@holytshirt Can pick up as part of work to support a binary outbox.
