### ISSUE TITLE
Support Kafka for Task Queues

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#248]
We shoud support Kafka if we can. As it has a pub-sub architecture it should be amenable to implementing in our pub-sub architeture

https://en.wikipedia.org/wiki/Apache_Kafka

Kafka is becoming increasingly prevalent and it would help increase our range if we could add it to our list o supported middleware

**Comment by whunsley** [comment]
Looking at picking this up.  First of all do we agree that https://github.com/confluentinc/confluent-kafka-dotnet will be the client?

**Comment by GrooveCS** [comment]
Microsoft currently supports the public using this implementation. It a commercially supported by them and your suggestion makes sense.

**Comment by iancooper** [comment]
@whunsley is now the owner of this one

Agreed on the client

**Comment by iancooper** [comment]
Beta is out
