### ISSUE TITLE
.net core default dependency injection example.

### ISSUE THREAD

**Issue by BringerOD** [BrighterCommand/Brighter#249]
Does anyone have an implementation using the default dependency injection that comes with .net core?

**Comment by JosephWoodward** [comment]
Would be interested in seeing this too 👍

**Comment by dstockhammer** [comment]
When I last checked, the default container didn't support open generics, thus wasn't compatible.
But I think that may have changed now, so I'll revisit when I get a chance.

**Comment by iancooper** [comment]
There is a discussion here: https://gitter.im/iancooper/Paramore see that as well

**Comment by BringerOD** [comment]
Thanks!  Great discussion.

**Comment by dstockhammer** [comment]
Can confirm that open generics are now supported: https://github.com/BrighterCommand/Darker/blob/master/src/Paramore.Darker.AspNetCore/ServiceCollectionExtensions.cs

I added an AspNet DI integration package for Darker, the integration looks like this: https://github.com/BrighterCommand/Darker/blob/master/samples/SampleApi/Startup.cs#L18-L31

Will look to do something similar for Brighter. I had to tweak the builder a little bit though...

**Comment by brainwipe** [comment]
For those following this (like me), @dstockhammer has kindly started an implementation here (with RC nuget package): https://github.com/dstockhammer/Paramore.Brighter.AspNetCore

You can get the nuget package too. If you're using VS2017 UI then don't forget to check "Include prerelease".

Thank you, Daniel, your implementation is much better than the one I came up with!

**Comment by JosephWoodward** [comment]
Oh nice!

NuGet package is [here](https://www.nuget.org/packages?q=Paramore.Brighter.AspNetCore) for anyone interested.

**Comment by iancooper** [comment]
OK, I am going to mark this issue as done and close. Hopefully, @dstockhammer and I can talk about moving this into the org repo or contrib
