### ISSUE TITLE
DepositPostAsync doesn't work with multiple concrete types of events.

### ISSUE THREAD

**Issue by andrei-tatar** [BrighterCommand/Brighter#2495]
### Describe the bug
Calling `DepositPostAsync` with a generic type `IEvent` argument but multiple concrete types instances, fails to post the messages. 
It fails to convert the messages to requests.

### To Reproduce
```csharp
var events = new List<IEvent>
{
  new ConcreteTypeEvent1(),
  new ConcreteTypeEvent2()
};

await commandProcessor.DepositPostAsync(events);
```

### Exceptions (if any)
> Specified argument was out of the range of valid values. (Parameter 'No message mapper registered for messages of type: IEvent')

### Further technical details
Brighter version in use: 9.2.4

Had a look over the CommandProcessor class and it seems the messages are grouped by their concrete type by method `SplitRequestBatchIntoTypes` but `BulkMapMessages` doesn't actually take into account the concrete type, it uses the generic argument <T> when mapping them to messages. I think an easy fix would be to pass the type (`batch.Key`) to `BulkMapMessages` (have a non-generic version of it that gets called by the generic version?).

https://github.com/BrighterCommand/Brighter/blob/d34375f695e0bdf9ef96ba496ea7993271d955b1/src/Paramore.Brighter/CommandProcessor.cs#L658

**Comment by iancooper** [comment]
@andrei-tatar I know that using the dynamic keyword on the parameter should preserve the original type. That fix tends to work here.

@preardon Any thoughts?

**Comment by preardon** [comment]
I'll have a look tomorrow, write a test, and see what I can come up with.

**Comment by iancooper** [comment]
@preardon Try using dynamic at the call site, just for me :-D

**Comment by preardon** [comment]
I've gone over this a few times tonight and given the use of Generics There does not appear to be a straight forward way to support this. @andrei-tatar  I've looked at your suggestion of passing in a type and keep getting stuck on not know the Type for the generics further down the field.

@iancooper  I suppose the real question here is, do we want to support this or Check and throw if multiple concrete types are detected in the list?

**Comment by andrei-tatar** [comment]
If it's generics all the way down, it should be possible to use reflection to generate the method signature with the generic type at the top. Not pretty, but it works :)

**Comment by iancooper** [comment]
@preardon We could talk about at the next meeting, see if we can divine what is going on. Do you have a test somewhere I can look at?

**Comment by preardon** [comment]
@iancooper I have just pushed my failing test, I can have a chat with Andrei to look into his reflection suggestion above as well

**Comment by preardon** [comment]
This is in the mainline and will be shipped with the next release, Thanks @andrei-tatar  for the assistance with this one
