### ISSUE TITLE
Add support for MySql as a Message Store

### ISSUE THREAD

**Issue by dcomartin** [BrighterCommand/Brighter#250]
I'd take a shot at this if its worthwhile.   There is a netstandard1.3 of an ado.net MySql provider that would be required: https://github.com/mysql-net/MySqlConnector

**Comment by JosephWoodward** [comment]
What about Dapper? That supports .NET Standard and MySQL?

**Comment by dcomartin** [comment]
Dapper sits on top of IDbConnection correct? You still need an impl of it.

**Comment by JosephWoodward** [comment]
Yeah, and come to think of it you do a similar thing (require the Postgres connection library) when using Postgres so ignore my comment :D

**Comment by Pothulapati** [comment]
@JosephWoodward I'm working on the Postgres implementation for the Message Store Right now. I do think having a consistency using Dapper API is worth looking after.

I think @iancooper should give this a thought.

**Comment by dcomartin** [comment]
After looking at the sqlite impl, not much would be different since everything is based on ado.net and DbConnection/Command etc.

**Comment by iancooper** [comment]
It's a tricky one. Franky given the simplicity of the code needed I am inclined to recommend ADO.NET raw as being probably the fastest approach (that's all Dapper is doing really).

The other advantage of us just using ADO.NET is that as we don't take a dependency on Dapper, that is one less potential conflict for implementers to struggle with, where they or another dependency uses Dapper but a different version.

There is a definite trade-off here: leverage other folks OSS work (as we do with Polly) and risk assembly binding issues, and do it yourself and end up with a NIH receating the wheel issue. Where the lib is internal, and not exposed (as Polly is) I might be inclined to avoid deps outside of the NET SDK where possible.

OIbviously we will end up with drivers/clients for various Dbs, stores etc. I'm not sure we can avoid that.

It should be easy enough for folks to recompile most of the assemblys containing our concrete implementations if they have to though.

**Comment by iancooper** [comment]
PS @dcomartin Yes we would love a PR for that. Please go for it :-)

**Comment by dcomartin** [comment]
Ran into an issue with the MessageStore.  Specifically the fact that a `Message.Header.TimeStamp` doesn't contain any milliseconds.  When calling `messageStore.Add`, the records are not always persisted in the order they were added.  Yes, really.  And since there is there are no milliseconds on the `Message.Header.TimeStamp`, ordering by the Timestamp column doesn't help any.

This is ultimately a problem in this situation:

 ```csharp
Add(message1);
Add(message2);
Add(message3);
Get(1,3); // Should be message3, but it may not be.
```

Is there any reason why in the sqlite and MSSQL the Timestamp of the message is not `DateTime.UtcNow`?

**Comment by dcomartin** [comment]
Turns out they are being inserted but there is no logical way to sort it to get them in the order they were inserted with the schema I was using.  I ended up adding timestamp column that gets set with NOW(3) in which I can order by.
