### ISSUE TITLE
DefaultPolicy cannot be used as a IAMPolicyRegistry to fulfilll CommandProcessorBuilder.Policies argument

### ISSUE THREAD

**Issue by awright18** [BrighterCommand/Brighter#263]
In this example DefaultPolicy fails the check for having policies which it does have.  

> var commandProcessor = CommandProcessorBuilder.With()
>                 .AutofacHandlers(builder, settings =>
>                     settings.WithCommandsAndHandlersFromAssembly(commandAssemblies)
>                 ).Policies(new DefaultPolicy())
>                 .NoTaskQueues()
>                 .RequestContextFactory(new InMemoryRequestContextFactory())
>                 .Build();

"The policy registry is missing the CommandProcessor.RETRYPOLICY policy which is required" 

This is because DefaultPolicy's implementation of IAmPolicyRegistry.Has always returns false.  I am trying to build some simplified configuration extensions and want the option of passing custom policies or just using DefaultPolicy.  

Is it possible this will be changed? Of course I can work around the issue, but was curious if this is the actual intended behavior of DefaultPolicy.

**Comment by iancooper** [comment]
Curious. Let me have a look.

**Comment by holytshirt** [comment]
fixed v8.0.*
