### ISSUE TITLE
Question - implementing synchronous and asynchronous projections

### ISSUE THREAD

**Issue by brainwipe** [BrighterCommand/Brighter#266]
Hello! I'd like to check my thinking. 

I am implementing projections using Postgres as a doc store (via Marten). When a Command is raised, I want the Handler to update the persistence layer (all good) and then generate projection documents. My question is how best to do that.

For example, I have a the `CreatePatientCommand` and `CreatePatient` Command Handler. 

```
public class CreatePatient : RequestHandler<CreatePatientCommand>
{
        private readonly IWriteRepository<Patient> patientRepo;
        // Chopped out the DI constructor        

        public override CreatePatientCommand Handle(CreatePatientCommand command)
        {
              // I'm going pseudocode for the build for brevity
              Patient patient = new PatientBuilder(command).Build;
              patientRepo.Add(patient);

              return base.Handle(command);
        }
}
```

So I want two projections: `PatientDetail` and `PatientSummary` that takes the new `patient`, creates two JSON documents. I could add that after `patientRepo` using a mystical `documentStore` like so:

```
              patientRepo.Add(patient);
              documentStore.Reproject<PatientDetail>(patient);
              documentStore.Reproject<PatientSummary>(patient);
              return base.Handle(command);
```

These would meet my synchronous needs. However, part of me feels that the Command Handler shouldn't care what projections are needed. It's almost like a need to set the new patient into the `Context.Bag` and make a terrifyingly named `CreatePatientProjectionHandler` such as:

```
public class CreatePatientProjectionHandler: RequestHandler<CreatePatientCommand>
{
        private readonly IDocumentStore documentStore;

        // Chopped out the DI constructor

        public override CreatePatientCommand Handle(CreatePatientCommand command)
        {
              Patient patient = (Patient)Context.Bag["Patient"];
              documentStore.Reproject<PatientDetail>(patient);
              documentStore.Reproject<PatientSummary>(patient);
              return base.Handle(command);
        }
}
```

Naming aside, that's better than including the projections inline but I'd need to duplicate this handler for all the other patient based commands. So I'd rather do something like:

```
public class CreatePatientProjectionHandler: RequestHandler<CreatePatientCommand, DeletePatientCommand, MyOtherPatientCommand, etcCommand>
```

Which is nonsense, of course. I need a Handler that is more specific than the [Logging example](http://paramore.readthedocs.io/en/latest/BuildingAPipeline.html#implementing-a-pipeline) but not as specific as my `CreatePatient` Handler. I'm pretty sure I need to create a Projection Attribute for managing the pipeline but I am unsure how.

## Async Projections for Reporting
I also need a second set of handlers that build dashboards and reports. These projection handlers would take the updated data and not need to run synchronously.

Does this sound reasonable? Have I missed something obvious?

Many thanks in advance for your help.

**Comment by iancooper** [comment]
@brainwipe  Just a note, its easier to ask questions in Gitter as we get notifications there: https://gitter.im/iancooper/Paramore

I woud raise an event from the command handler, and build the projections in the event. I might well do that on a worker, over a queue, using Post, over in-process by just raising an event from within the command handler.

You could do projection updates as an orthogonal action in another handler, and push the required information into a context bag as shown; I woud tend to avoid that because raising an event gives you more flexibility by decoupling where it is handled. It works though, if you prefer.

I suspect that your soluton for reporting is closer to how I would rebuild projections.
