### ISSUE TITLE
Corrections in "Hello World" and "Greetings Example" examples.

### ISSUE THREAD

**Issue by DevJonny** [BrighterCommand/Brighter#277]
After running through the "[Hello World](https://www.goparamore.io/hello-world/)" and "[Greetings Example](https://www.goparamore.io/greetings-example/)" I noticed there were a few discrepancies between the code in the tutorials and the code in [Brighter/samples](https://github.com/BrighterCommand/Brighter/tree/master/samples).

### Hello World

Step two should be: 
- `PM> Install-Package Paramore.Brighter`

Step three - Requests and Request Handlers:
- There is a minor typo of  `...command GreetingCommandwe`
- In the code example the `logger` shouldn't be being passed a parameter to `SimpleHandlerFactory` ctor

Step four - Our First Handler
- There is a minor type of `...class fromIHandleRequests<TRequest>`
- In the code example the first line should read
`class GreetingCommandHandler : RequestHandler<GreetingCommand> { ... }`

Link to the "Greetings Example" at the end of the tutorial links to GitHub rather than the goparamore.io [page](https://www.goparamore.io/greetings-example/)

### Greetings Example

Opening paragraph:
- Link to "Greetings Example" should be pointing to the [samples](https://github.com/BrighterCommand/Brighter/tree/master/samples)

Step 6:
- TopShelf.HostFactory call is missing a type param on .Service
`HostFactory.Run(x => x.Service<GreetingService>(sc => {...}));`

Step 7: 
- `container.Register,
GreetingEventHandler>();` should be `container.Register<IHandleRequests<GreetingEvent>, GreetingEventHandler>();`
- `subscriberRegistry.Register GreetingEventHandler>();` should be `subscriberRegistry.Register<GreetingEvent, GreetingEventHandler>();`
- `var retryPolicy = Policy.Handle()...` should be `var retryPolicy = Policy.Handle<Exception>()...`
- `var circuitBreakerPolicy = Policy.Handle()` should be `var circuitBreakerPolicy = Policy.Handle<Exception>()`
- `var rmqMessageProducerFactory = new RmqMessageProducerFactory(rmqConnnection);` should be removed
- `InputChannelFactory(rmqMessageConsumerFactory, rmqMessageProducerFactory))` should be `InputChannelFactory(rmqMessageConsumerFactory))`
- `.Connections(new[] { new Connection(...) })` should be `.Connections(new [] { new Connection<GreetingEvent>(..) `})

Step 8:
- First code block is an amalgamation of all the following code blocks and text including the beginning of Step 9

**Comment by mit-jamie-clayton** [comment]
#336 #335

**Comment by holytshirt** [comment]
@skatersezo and this too

**Comment by alanmynah** [comment]
@holytshirt, this one is fixed too.

**Comment by holytshirt** [comment]
Awesome, thank you!
