### ISSUE TITLE
Support Azure Service Bus 

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#28]

**Comment by yiannistri** [comment]
So far we can publish messages to an Azure topic but would need to wrap the first connection call in a retry policy as we do for RabbitMQ. Opted for Polly instead of the build-in retry classes to keep the two implementations consistent. Now working on the message receiver.

**Comment by iancooper** [comment]
Cool. Yes stick with Polly so we can use on approach, I think.

**Comment by iancooper** [comment]
@dstockhammer now has this
