### ISSUE TITLE
Create a contrib example using MessagePack

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#282]
I don't suspect that JSON serialization is our biggest weakness, but it would be good to show how to lower the payload size quickly for folks that need that in a contrib project.

In essence message mapper will handle this for you, but folks like examples

MessagePack: https://msgpack.org/index.html
.NET Lib: https://github.com/neuecc/MessagePack-CSharp

**Comment by holytshirt** [comment]
@skatersezo is going to pick this up
