### ISSUE TITLE
Depend on a signed version of the Polly library

### ISSUE THREAD

**Issue by rvanmaanen** [BrighterCommand/Brighter#286]
Hi,

I was experimenting with the latest .NET Core 2.1 preview, especially the new feature that allows configuring HttpClients at startup, together with message handlers and errorhandling and then injecting a typed client. The errorhandling can be done with an very cool extension method from the NuGet package Microsoft.Extensions.Http.Polly. This is documented at [Polly and HttpClientFactory](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory)

However, this extension method uses the signed version of Polly. Now the issue is that I'm using Brighter as well, which is using the unsigned version of Polly. This results in these nasty warnings: `No way to resolve conflict between "Polly, Version=5.9.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc" and "Polly, Version=5.9.0.0, Culture=neutral, PublicKeyToken=null". Choosing "Polly, Version=5.9.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc" arbitrarily`

It would be great if a Brighter-Signed package could be created, which uses signed packages where possible too. My next stop would then be [Paramore.Brighter.AspNetCore](https://github.com/dstockhammer/Paramore.Brighter.AspNetCore) to submit the same request there, as I'm using that NuGet package to add Brighter to my webservices. :)

You can see the warning yourself if you have a look at this solution: https://github.com/rvanmaanen/httpclientfactory-polly-brighter (you'll need the latest .net core 2.1 preview installed and preferably the latest preview of visual studio too)

Another issue that occurs too: When adding both Brighter and Microsoft.Extensions.Http.Polly, it's required to explicitly reference Polly-Signed too, else this error occurs: `The type 'PolicyBuilder<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Polly, Version=5.8.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc'`. Probably has to do with the different versions of Polly being used together as well.

Ignoring all the above, you end up with a compile error which I can't get out of the way when trying to build my own Policy by doing something like `var myPolicy = Policy.Handle<HttpRequestException>();`. The error is: `The type 'Policy' exists in both 'Polly, Version=5.9.0.0, Culture=neutral, PublicKeyToken=null' and 'Polly, Version=5.9.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc'`. I updated the code at https://github.com/rvanmaanen/httpclientfactory-polly-brighter to show this.

**Comment by iancooper** [comment]
I hate signed assemblies. I despise the ground they were built on.

That said, we will see what we can do to fix this. perhaps some sort of alternative package (although I am minded to call it Paramore.Brighter.Infected

**Comment by rvanmaanen** [comment]
Hehe, I can live with Infected :-) Great that you brought it up at the Microsoft team too, let's see how this can be resolved.

**Comment by iancooper** [comment]
So it looks like Polly are going to [drop the unsigned version](https://github.com/aspnet/HttpClientFactory/issues/105).  That will clarify the ecosystem, but means we will have to release a new version of Brighter that uses the signed version of the code instead. We can do that, and probably should ahead of 2.1 RTM, We will have to notify our consumers of the issue, and their need to move to the signed version of Polly.

The pain point here is that we also have to upgrade our code as Polly has changed their interface, requiring us to change our code. We were going to do this anyway, but having to move forward versions will force our hand on doing this now.

**Comment by iancooper** [comment]
We'll use this issue to track creating a version of Brighter that depends on a signed version of Polly, and track creating a signed version of Brighter separately.

**Comment by iancooper** [comment]
Just to keep you in the picture. In order to create a version that depends on a signed version we have two dependencies. (1) We need to move to the latest Polly API as we are using obsolete features that won't be supported in that release (2) We need to wait for the signed-only version of Polly from this: https://github.com/App-vNext/Polly/issues/442

The signed version of Brighter issue is here: https://github.com/BrighterCommand/Brighter/issues/287

**Comment by rvanmaanen** [comment]
Thanks, I was monitoring all the issues as well. We don't really need a signed version of Brighter (just a signed Polly), but thought you'd want to follow the current Polly strategy by creating a signed and non signed package. Looks like they will drop the non signed package, do you plan on doing the same in the future?

Anyway, thanks for fixing this!

**Comment by rvanmaanen** [comment]
Polly 6.0.1 has been released!

**Comment by iancooper** [comment]
Yeah, I just saw

**Comment by holytshirt** [comment]
This is done, and pushed to NuGet.
