### ISSUE TITLE
Support Amazon SQS

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#29]

**Comment by iancooper** [comment]
Reopened because this needs work

**Comment by iancooper** [comment]
For inspiration: https://github.com/justeat/JustSaying
https://aws.amazon.com/sqs/

**Comment by aejay-rs** [comment]
Are there any specific improvements planned for this? We've had a few reliability issues following service outages at AWS, but we aren't sure if it's something we've configured wrong or if there's a library issue.

The most recent happened yesterday, starting with what looks to be 500 error coming back from SQS itself. The stack trails back to a call from `Paramore.Brighter.MessagingGateway.AWSSQS.SqsQueuedRetriever.<GetMessage>`

```
MessagePump: Exception receiving messages from https://sqs.us-east-1.amazonaws.com/[queue-endpoint] on thread # 7
Amazon.SQS.AmazonSQSException: We encountered an internal error. Please try again. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (500) Internal Server Error. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
```

No service has 100% uptime, so issues like these are expected from time to time, but once the dispatcher hit this exception, it stopped fetching/processing messages until the service was restarted.

Does any particular configuration issue come to mind that we should look out for? What other information can I provide to help dig into this further?

**Comment by iancooper** [comment]
Hi @aejay-rs 

We don't know of many production users on SQS (you may be it). We do have a project to improve reliability across our transports and SQS was on my list (because we are contemplating whether to switch from RMQ across AZs for some workloads).

As a result we suspected that we might have some issues during failure. We would need to look at how we handle exceptions on the receive call within the SQS transport provider. It may simply be a case of catching this error, turning it into a channel exception, and they relying on the message pump (which works across all the transports) recognizing a channel exception and retrying the connection.

If you feel up to looking into a PR, that would be great. If not I'll try to get to this asap.

**Comment by aejay-rs** [comment]
cc @adamwrs

When we find time, we'll try to reproduce this in a lower environment to dig up more details. If we can learn some lessons and contrib something useful, we'll open a PR.

**Comment by iancooper** [comment]
@aejay-rs @adamwrs

Cool. We have a push on our transports right now, and my looking over SQS is behind the Redis project.  But if you guys get it to it first, I would love the help making sure that it is 'battle tested'

**Comment by iancooper** [comment]
OK I have this now

**Comment by iancooper** [comment]
Closed as a duplicate now
