### ISSUE TITLE
MessagingGateway.AWSSQS Needs more config for AWS Clients, ie Region

### ISSUE THREAD

**Issue by drewsuccess** [BrighterCommand/Brighter#297]
Paramore.Brighter.MessagingGateway.AWSSQS using various Amazon service clients and only passes in credentials.  We are using this with .NET Core and would like to specify the region as well as credentials for SqsMessageProducer for example.  A simple fix would be to have constructor overloads that also take in RegionEndpoint. 

A longer term might abstract out the creation of Amazon service clients so we can determine how they get created as a client.

**Comment by drewsuccess** [comment]
Example Pull Request #298

**Comment by iancooper** [comment]
Do you want to leave this open for now, so that we can look at the other issues here. We know this needs a full review.

**Comment by drewsuccess** [comment]
Region was the specific need, using the fork of it with just those changes.  If there were other planned updates/review that is also welcome.  I'm open to either leaving it open or closing since the specific hurdle has been passed.
