### ISSUE TITLE
Obfuscate logs of sensitive data

### ISSUE THREAD

**Issue by jablamas** [BrighterCommand/Brighter#299]
We would need a way to obfuscate certain parts of the messages logged by Brighter on ElasticSearch. Is there a simple way to configure that functionality? Thanks!

**Comment by iancooper** [comment]
Not out of the box, although we use liblog, so essentially you provide the logger, not us. Otherwise I have not thought about it as yet.

Can you give me an idea of what it is you need to obfusticate? I assume there is some plain text information in the message body etc?

**Comment by jablamas** [comment]
Ok Ian, thanks for your quick response. Your assumption is correct, we are trying to obfuscate some parts of the string being logged. We find a problem when trying to use Destructurama package for Serilog: https://github.com/destructurama/attributed 
This package requires certain syntax for the variables in the log message, but on the other hand we are relying on the handlers:
https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter/Logging/Handlers/RequestLoggingHandler.cs
...that call the logging functions (logger.Value.InfoFormat...) without the needed syntax. I suppose that we should find a workaround for this.

Thank you!

**Comment by iancooper** [comment]
Added to #242

**Comment by iancooper** [comment]
@holytshirt If you are looking at logging, worth noting if we can obfuscate for PII etc

**Comment by preardon** [comment]
@jablamas will Destructurama work now that we have the ability for Structured Logging?

**Comment by iancooper** [comment]
@preardon Closing this issue for now, based on your comment, and lack of activity on it
