### ISSUE TITLE
On RMQ Producer we don't retry following a connection reset, we probably should

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#303]
When the RMQ Producer tries to send to the broker and fails, we retry, break the circuit and eventually give up. When we give up, we reset the connection in the pool, on the assumption that it is no longer valid.

If we have just lost contact with a node, because it is paused, being upgraded etc. we really want to try and send the message on the new connection before we give up.

So we should retry once we have reset the connection.

Obviously this could be infinite so we need to break the retry following a connection reset after a defined number of retries as a 'give up, all attempts to reach broker failed'.

We might want to do this after the first reset fails to clear the error.

**Comment by homcl** [comment]
I'll take this one. Pls assign me to it.

**Comment by holytshirt** [comment]
@homcl  I think you did this already?

**Comment by holytshirt** [comment]
Fixed with this commit https://github.com/BrighterCommand/Brighter/commit/28445044d2a48df20b79876e79fa4286ec133c60
