### ISSUE TITLE
Replace the current brighter policy registry with Polly

### ISSUE THREAD

**Issue by SeanFarrow** [BrighterCommand/Brighter#307]
Hi,

It would be good, as we have now done with Darker,  to replace brighter's own PolicyRegistry with the one from Polly.
I am happy to do the work as before if this is wanted.
Cheers
Sean.

**Comment by iancooper** [comment]
We could. Have a stab and create a PR. Come over to the Gitter channel if you have questions.

**Comment by iancooper** [comment]
If you wanted to pick up #263 while you are there @SeanFarrow ?

**Comment by SeanFarrow** [comment]
@IanCooper,
I’ll pick up both over the weekend.

**Comment by iancooper** [comment]
Thanks @SeanFarrow

**Comment by SeanFarrow** [comment]
@IanCooper,
You have a defaultPolicy class that implements the IAmAPolicyRegistry interface. It just returns policies given a name. Where should these be registered. I don’t really want to sub class the polly policy registry if I can help it.
Is there a reason default policies are added in the first place, I’m writing a microservice based system, so want my own policies for each service. Should we have an IRegisterPolicies interface?
Thoughts?

**Comment by iancooper** [comment]
We added this to prevent a 'fail' when you didn't register even a basic policy. We can review that if we are moving away from our own policy registry.

**Comment by SeanFarrow** [comment]
What would the ideal scenario be, given people will want to use there own policies.
Where are policies used currently?

**Comment by iancooper** [comment]
@SeanFarrow We liked the idea of having the building blocks be replaceable, for whatever reason. Hence we let you define your own PolicyRegistry if you wanted to. Why not? But now Polly has one, there does not seem to be too much point in you defining your own, apart from backward compatibility. But I am all for simplifying.

So really, at that point we just need to ensure that the builder guides you toward successful setup. Which means either we throw an exception if you don't create the policies we depend on, define them for you, or some combination.

Whilst I like the idea of us checking for them, and throwing a configuration exception, I also like the idea that you can simply ask us to add our default policies, for the ones we use internally. That came from experience of folks mis-configuring the system, and so I would be loathe to drop it, unless new experience trumps that

**Comment by SeanFarrow** [comment]
@IanCooper,
I'm just implementing this now, Is it the CommandProcessorBuilder or the dispatcher that need to define the default policies?
I'm thinking about adding a way to register any policies within a policy registry, during the building process, so probably adding another interface and implementing this in the CommandProcessorBuilder. I don't want people to be able to add to a PolicyRegistry once the command processor has been built as this wouldn't make sense, and would mean people could remove policies you use.
Thoughts?

**Comment by iancooper** [comment]
@SeanFarrow The Command Processor Builder. It looks as though we already throw if you don't include the policies that we require, so you just need to change the type of the parameter on Policies. For DefaultPolicy, why not return a Polly PolicyRegistry with the policies from the DefaultPolicy object. That way we will keep the same behavior?

**Comment by SeanFarrow** [comment]
@IanCooper,
Makes sense. Although, the DefaultPolicy object isn’t strictly required as it only implements IAmAPolicyRegistry which is now not needed. Perhaps we should require a user to pass a polly policy registry to the CommandProcessorBuilder?

**Comment by iancooper** [comment]
DefaultPolicy is really intended to provide the policies that **we** need over the end user. We use them to retry our connections to MoM. So we don't need the implementation, we need the effect of the implementation, which is that if you don't provide us with your own policy registry, we will provide one, with our default policies added.

The idea is that you might not want to create your own policy registry, just to support our needs, and that we ought to have defaults for **our** needs.

So you can return a Polly policy registry from the method call, but you need to add the policies that the DefaultPolicy currently defines.

**Comment by holytshirt** [comment]
@SeanFarrow  I don't know how far you got on this, this work has just been added to master and we are looking to release soon.

**Comment by SeanFarrow** [comment]
That’s fine, I’ve mostly been involved with the upgrade to the PolicyRegistry/polly code clean up.
We’ve also switched away from brighter/darker for various reasons within the project.

**Comment by holytshirt** [comment]
Thanks @SeanFarrow I replaced IAmAPolicyRegistry with IPolicyRegistry<string> and now just use the PolicyRegistry from Polly.

This will be in release v8, out soon :)

**Comment by iancooper** [comment]
Think that @holytshirt has completed this one

**Comment by holytshirt** [comment]
Fixed in V8.0.*
