### ISSUE TITLE
[Bug] Azure Service Bus - RequestType

### ISSUE THREAD

**Issue by ransht** [BrighterCommand/Brighter#3070]
### Describe the bug
When attempting to use the `RequestType` property in the `AzureServiceBusPublication` class as shown in the sample code(**ASBTaskQueue.GreetingsSender**), it appears that the `RequestType` is missing from the `AzureServiceBusPublication` class, which inherits from `Publication`.

```
                    new AzureServiceBusPublication
                    {
                        Topic = new RoutingKey("greeting.event"),
                        RequestType = typeof(GreetingEvent)
                    },
```

### Further technical details
- Brighter version - tried 9.7.8 and event 10.0.0-preview.3
- Include the output of `dotnet --info`
```
-  dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: arm64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.417 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```
- The OS -MacOs 
- Code Editor: Jetbrains Rider 

#### Additional Context
I attempted to utilize the `RequestType` property in the `AzureServiceBusPublication` class, but it appears to be absent from the class definition, causing issues with my implementation.

Also another question, Azure Service Bus support queues and topics.
How can I use this and differentiate between them?

**Comment by preardon** [comment]
@ransht AzureServiceBusPublication inherits directly from Publication which has it there' what issues are you experiencing

**Comment by iancooper** [comment]
@ransht I think that this is a V9 vs V10 issue. If you want to look at the V9 samples use the release/9X branch

**Comment by iancooper** [comment]
@ransht Did you check on V9 vs V10 here?

**Comment by ransht** [comment]
At first I didnt
