### ISSUE TITLE
RMQ Transport: Support Blocked Connections Notifications for Diagnostic Purposes

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#309]
We should subscribe to Blocked Connections Notifications so  that we can notify via the logs that we have a blocked connection to highlight resource or synchronization issues.

**Comment by homcl** [comment]
https://www.rabbitmq.com/connection-blocked.html

**Comment by iancooper** [comment]
@homcl  Are you volunteering?

**Comment by holytshirt** [comment]
Yes she is!

**Comment by homcl** [comment]
Hi Ian

I am volunteering to do this issue. I wasn’t sure where to start so Toby found this link. I’ll give it a read. I need to push a minor change to #721 (persist message) also.

Hope

Hope Mcleod | Junior Developer
Huddle – Transform the way you work!

Hope.mcleod@huddle.com



Ninian Solutions Ltd (trading as Huddle) is registered in England & Wales at Aldgate Tower, 2 Leman Street, London, UK (company number 05777111) and its U.S subsidiary Huddle Inc., a Delaware Corporation, at 156 2nd Street, San Francisco, CA, U.S.
