### ISSUE TITLE
Issue with Call() method to CommandProcessor

### ISSUE THREAD

**Issue by satishviswanathan** [BrighterCommand/Brighter#318]
I've trying to use Call() to implement Request - Reply using RabbitMQ. I'm seeing 2 issues.

1. The interface IAmACommandProcessor does not have the definition for Call().
2. Using the Call() I'm able to send the request and process it and send a response back to the client but found that the queue created for this purpose is not getting deleted once the response is send back. I'm also seeing the same issue while running the sample project too.

![image](https://user-images.githubusercontent.com/17437409/50526393-5e55ac80-0aa7-11e9-9186-071a80108968.png)

Any help on this issue is appreciated

**Comment by iancooper** [comment]
@satishviswanathan Thanks for reporting this, I'll take a look at these issues and see what is up.

**Comment by iancooper** [comment]
I've pushed a fix to the master for the missing method on the interface. I need to look into why the queue does not delete. Are you sure that the queue is still there when you restart the broker?

**Comment by iancooper** [comment]
OK, I understand why this is happening now. I just need to ponder the best approach to the fix (how much to expose to the client around this, and how much to just manage). But I understand the issue here now.

**Comment by DevJonny** [comment]
While looking into this (I believe it's actually fixed based on our Production code) I found another issue which I've created a [ticket](https://github.com/BrighterCommand/Brighter/issues/1699) for.

**Comment by iancooper** [comment]
Thanks @DevJonny, I expect you might be the first team member to use it in anger

**Comment by iancooper** [comment]
@DevJonny Can I close this one?

**Comment by DevJonny** [comment]
Yes @iancooper I meant to come and say exactly that!

**Comment by iancooper** [comment]
Thanks @DevJonny
