### ISSUE TITLE
System.Reflection.ReflectionTypeLoadException when enumerating Assemblies

### ISSUE THREAD

**Issue by SteveBush** [BrighterCommand/Brighter#3254]
### Describe the bug
In ServiceCollectionBrighterBuilder, there are several methods that enumerate assemblies and call DefinedTypes on the assembly to find a particular interface, e.g. IAmAMessageMapper.  The call to DefinedTypes under NetCoreApp3.1 will generate a System.Reflection.ReflectionTypeLoadException as "System.Web.UI.ICallbackEventHandler" from "System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" is not present.  

The fix is to enumerate the assemblies in a try/catch block that handles the System.Reflection.ReflectionTypeLoadException exception and continues on to the next assembly.  I can work around this by passing in my own list of assemblies and calling the registration functions separately.

### To Reproduce
Build an xUnit test project targeting netcoreapp3.1.  Create a default Host.  AustoFromAssemblies should throw a System.Reflection.ReflectionTypeLoadException exception.
```
           return Host.CreateDefaultBuilder()
               .ConfigureServices((hostContext, services) =>
               {
                   IBrighterBuilder brighterBuilder = services.AddBrighter().AutoFromAssemblies();
               })
               .Build(); 
```

### Exceptions (if any)
System.Reflection.ReflectionTypeLoadException

```
System.Reflection.ReflectionTypeLoadException
Unable to load one or more of the requested types.
Could not load type 'System.Web.UI.ICallbackEventHandler' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load type 'System.Web.UI.ICallbackEventHandler' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
```

**Comment by SteveBush** [comment]
Below is my hack for getting around the System.Reflection.ReflectionTypeLoadException error. Basically, I materialize the DefinedTypes enumeration and skip the assembly.  This is fine for me as my assemblies load fine.  The fix should only skip at the type level.

```
    /// <summary>
    /// Scan the assemblies provided for implementations of IHandleRequests, IHandleRequestsAsync, IAmAMessageMapper and register them with ServiceCollection.
    /// </summary>
    /// <param name="brighterBuilder">Brighter builder.</param>
    /// <param name="extraAssemblies">>The extra assemblies to scan.</param>
    /// <returns>Brighter builder with added assemblies.</returns>
    public static IBrighterBuilder CoreAutoFromAssemblies(this IBrighterBuilder brighterBuilder, params Assembly[] extraAssemblies)
    {
        if (brighterBuilder is null)
        {
            throw new ArgumentNullException(nameof(brighterBuilder));
        }

        IEnumerable<Assembly> appDomainAssemblies = AppDomain.CurrentDomain.GetAssemblies().Where(a =>
            !a.IsDynamic && (!a.FullName?.StartsWith("Microsoft.", true, CultureInfo.InvariantCulture) ?? false) &&
            (!a.FullName?.StartsWith("System.", true, CultureInfo.InvariantCulture) ?? false));

        IList<Assembly> assemblyCandidates = [];

        // Remove offending assemblies
        foreach (Assembly assembly in appDomainAssemblies.Concat(extraAssemblies))
        {
            try
            {
                _ = assembly.DefinedTypes.ToList();
                assemblyCandidates.Add(assembly);
            }
            catch (ReflectionTypeLoadException)
            {
            }
        }

        Assembly[] assemblies = assemblyCandidates.ToArray();

        brighterBuilder
            .MapperRegistryFromAssemblies(assemblies)
            .HandlersFromAssemblies(assemblies)
            .AsyncHandlersFromAssemblies(assemblies)
            .TransformsFromAssemblies(assemblies);

        return brighterBuilder;
    }
```

**Comment by slang25** [comment]
`AutoFromAssemblies()` has an overload which allows for passing assemblies explicitly, this might be preferable as scanning all assemblies is likely costly perf wise.

That said, I think it's worth updating the default `AutoFromAssemblies()` method to catch `ReflectionTypeLoadException` just to make it a bit more happy-go-lucky. It also has a [`Types` property](https://learn.microsoft.com/en-gb/dotnet/api/system.reflection.reflectiontypeloadexception.types?view=net-8.0) which contains the types it _was_ able to load.

**Comment by SteveBush** [comment]
I use the AutoFromAssemblies only in my unit test code as a double check that I didn’t miss any assemblies that I manually added using the overload. You’re right in the that scanning performance should be avoided in production.

**Comment by slang25** [comment]
I'm mistaken, I thought the `AutoFromAssemblies(params Assembly[] extraAssemblies)` was actually a "don't scan, I'm doing the work", but it's not, it's "try to scan yourself, and I'll pass any additional assemblies you don't find".

**Comment by SteveBush** [comment]
Yes.  It would be good to get an option to supply your own assemblies.  I have created an extension (similar to above) that just calls the following with an array of assemblies.
```
brighterBuilder
            .MapperRegistryFromAssemblies(assemblies)
            .HandlersFromAssemblies(assemblies)
            .AsyncHandlersFromAssemblies(assemblies)
            .TransformsFromAssemblies(assemblies);
```
