### ISSUE TITLE
EOL of Brighter control library 

### ISSUE THREAD

**Issue by rajadas82** [BrighterCommand/Brighter#3332]
Hi

Is there any End of life support for Brighter controller? I’ve been advised to move from brighter to atlas by April 2025.

Can you please advise me?

**Comment by iancooper** [comment]
@rajadas82 We have not issued any end of life notification. Who did you receive that from?

**Comment by rajadas82** [comment]
Thank you Ian. Is angular17 is compatible with brighter control? The main driver behind the brighter to atlas migration is attributed to two factors 1. Need to switch from angular 16 to angular 17 (this part we are aware) 2. Due to non compatibility of angular 17 and brighter, the brighter to atlas migration is suggested. We are still doing all due diligence, any expert feedback much appreciated.

**Comment by iancooper** [comment]
I wonder if we are talking about different projects; we don't have any angular dependency and vice-versa. Do you mean a brightness control for the angular framework?

**Comment by iancooper** [comment]
Nothing to do with us
