### ISSUE TITLE
https://www.goparamore.io/hello-world/ references incorrect Github Repo

### ISSUE THREAD

**Issue by mit-jamie-clayton** [BrighterCommand/Brighter#335]
As a new developer to Brighter,
I want confidence in finding information quickly,
So I can become productive with the nuget packages.

## Steps to locate wrong URL.
- Navigate to 
- Locate the first paragraph with the words
> This tutorial takes you building a Hello World project. The walkthrough will build the example availabe in the Examples folder of Brighter available in the public repo at Hello World Example if you want to follow along there instead of typing in the code.
- Confirm the URL "Hello World Example" navigates incorrectly.

## Expected behaviour
- URL should be https://github.com/BrighterCommand/Brighter/tree/master/samples/HelloWorld

**Comment by holytshirt** [comment]
@skatersezo these are the same ones you found, hopefully fixed soon

**Comment by alanmynah** [comment]
@holytshirt, this should now be fixed. 

https://www.goparamore.io/hello-world

**Comment by holytshirt** [comment]
👍
