### ISSUE TITLE
Bug: DynamoDbOutbox Archiver Will Delete Undelivered Messages

### ISSUE THREAD

**Issue by jtsalva** [BrighterCommand/Brighter#3352]
### Describe the bug
The archiver finds messages to delete using [the following condition](https://github.com/BrighterCommand/Brighter/blob/d7ffd74204a49cec068a58c3746fd03800ae67dc/src/Paramore.Brighter.Outbox.DynamoDB/KeyTopicDeliveredTimeExpression.cs#L13):
```
Topic = :v_Topic and DeliveryTime < :v_SinceTime
```
[DeliveryTime default value is 0](https://github.com/BrighterCommand/Brighter/blob/d7ffd74204a49cec068a58c3746fd03800ae67dc/src/Paramore.Brighter.Outbox.DynamoDB/MessageItem.cs#L132), therefore undelivered messages can be deleted by the archiver.

Screenshot shows our Delivered index containing messages with `DeliveryTime = 0`
<img width="1652" alt="Screenshot 2024-10-14 at 20 39 39" src="https://github.com/user-attachments/assets/c94abb92-1b43-4f12-a845-a66dd1277b3d">

Due to #3351 I've not observed this to happen but I suspect it will be a problem?

### Proposed fix
Either add a condition to the dynamo query so that `DeliveryTime > 0` or make the default DeliveryTime be `null`.

### Further technical details
- Brighter v9

**Comment by dhickie** [comment]
It makes the most sense to omit the value when initially storing the record (which is not the same thing as setting it to `null` - `null` is a value). Otherwise every run of the archiver will be scanning the entire table and lead to unnecessary costs.

**Comment by iancooper** [comment]
Hi @dhickie and @jtsalva. Are we saying it is set to 0, or not set?

**Comment by jtsalva** [comment]
Right now the MessageItem constructor is explicitly setting to 0

**Comment by jtsalva** [comment]
>  omit the value when initially storing the record (which is not the same thing as setting it to null - null is a value)

@dhickie in C# isn't setting the value to `null` the way to omit from the dynamo index? I'm not aware of something like `undefined`, C# object properties will always have a default value?

**Comment by iancooper** [comment]
@jtsalva Is this one fixed?

**Comment by jtsalva** [comment]
#3390 should be the last one

**Comment by iancooper** [comment]
Thanks @jtsalva. Merged
