### ISSUE TITLE
https://www.goparamore.io/hello-world/ references incorrect Nuget Package

### ISSUE THREAD

**Issue by mit-jamie-clayton** [BrighterCommand/Brighter#336]
As a new developer to Brighter,
I want to practice creating code projects, by following on examples,
with out recieving Nuget package warnings,
So I can prepare myself for creating software using Brighter. 

## Steps to locate wrong URL.
- Navigate to
- Locate the paragraph with the words
> Step Two
> Install the Brighter.CommandProcessor package from NuGet
> PM> Install-Package Brighter.CommandProcessor
- Confirm the PM command causes an error "Can't find package".

## Expected behaviour
- Execute PM> Install-Package Paramore.Brighter
- Confirm the nuget package installs and works with the tutorial on the page.
- Confirm the tutorial and the github sample URL match (Sample seems to use full source code references vs nuget packages).

**Comment by holytshirt** [comment]
@skatersezo these are the same ones you found, hopefully fixed soon

**Comment by alanmynah** [comment]
@holytshirt, This is also now fixed

**Comment by holytshirt** [comment]
👍
