### ISSUE TITLE
Look at compiling against .NET Core on a branch, fix obvious issues where possible

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#45]
Get the core libraries building with dnx

Current blocker is System.Configuration, which will not be implemented in the coreclr.
A new configuration library is been built
- IConfiguration
  http://whereslou.com/2014/05/23/asp-net-vnext-moving-parts-iconfiguration/

**Comment by holytshirt** [comment]
Have a project.json file for command processor and have it building on .net4.5 + dnx4.5 + dnxcore5.
I also have Service Activator building on  .net4.5 + dnx4.5 . The dnxcore5 is half way there. I'll push a separate branch once I have this working. The biggest problem is the System.Configuration namespace has not been ported yet

**Comment by holytshirt** [comment]
The is a dnx branch https://github.com/iancooper/Paramore/tree/dnx now with project.json files in the commandProcessor and Service activator projects.  CommandProcessor was building until the System.Configuration namespace was brought in. **grumbles**

**Comment by holytshirt** [comment]
Just adding this extra information on the new forth coming configuration reader http://whereslou.com/2014/05/23/asp-net-vnext-moving-parts-iconfiguration/
So I don't lose it

**Comment by iancooper** [comment]
One option is for us to abstract out how we do configuration more, so that we can use different implementations. I would like to see us differentiate:

- Design time settings: ensure these are in code
- Machine settings: I don't think we have any of these but they should be in environment variables. The interesting one here is that in a Docker delivery you would probably have one ServiceActivator component per container so you could use environment variables for many settings, but in a VM you might well run multiple Service Activator instances and can't. In that case we either need a config alternate like an ini or yaml file, or we need to use a key-value store like Consul.
- Network settings: We should make it possible to put information that depends on network configuration in a key value store like Consul as well as an ini or yaml file for folks that don't have that infrastructure.

The positive thing here is we could change like this and support a range of configuration scenarios, which would make much more sense given the possible different deployment topologies we might finds ourselves in.

Thoughts @holytshirt ?

**Comment by holytshirt** [comment]
RabbitMQ going to rewrite their client for core: https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/148

**Comment by holytshirt** [comment]
look at trying AMPQ lite as message bus client https://github.com/Azure/amqpnetlite/releases/tag/v1.1.9-rc

**Comment by penderi** [comment]
Have you looked at https://github.com/StackExchange/StackExchange.Redis/tree/CoreCLR ?

**Comment by michaelklishin** [comment]
@holytshirt we updated our existing client to support .NET Core (in master, there's a NuGet feed). A new client is still on the roadmap but for a different reason (a new, modern .NET API without 9 years of baggage).

**Comment by holytshirt** [comment]
@michaelklishin thanks! I'm currently trying out your current client via the appveyor feed and have it working. 
Looking forward to the new shiny one ... Will it have async apis too?

**Comment by penderi** [comment]
+1 for async APIs ;-)

**Comment by iancooper** [comment]
I'm going to close this, we need to move to VS 2017 etc. but I will raise seperate issues
