### ISSUE TITLE
Support direct commands over HTTP

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#46]

**Comment by iancooper** [comment]
Internally at Huddle we use Hacktivator to allow you to POST a command or event directly the port, using OpenRasta as an intermediary. We find it useful for testing, although we don't expose it in production for documented resources. Damian Hickey has something similar for Cedar as OWIN middleware: https://github.com/damianh/Cedar.HttpCommandHandling At Huddle we will need to replace the Hacktivator functionality as we roll out Brighter that have enabled testing scenarios using Hacktivator, or they will continue to have dependencies on the earlier internal CommandProcessor. Others may find this useful too.

**Comment by damianh** [comment]
Will be very interested to see your take on this!

**Comment by iancooper** [comment]
This should be a separate assembly to avoid pulling this in with projects that don't want to use it.

**Comment by iancooper** [comment]
Closing for now, until we see demand
