### ISSUE TITLE
Create a github social media preview card

### ISSUE THREAD

**Issue by holytshirt** [BrighterCommand/Brighter#509]
Upload an image to customize your repository’s social media preview.

Images should be at least 640×320px (1280×640px for best display).
![repository-open-graph-template](https://user-images.githubusercontent.com/90132/57959714-f0e2d500-78fc-11e9-82c7-993e7cff7243.png)

**Comment by preardon** [comment]
@iancooper Was just playing around, thoughts?

![Brighter-Social-Card](https://user-images.githubusercontent.com/7712876/113601137-dd4bcf00-9638-11eb-8e1d-cd1cd7c9f030.png)

**Comment by iancooper** [comment]
I like the mix of cannon and letters. I like the colors.

Landing page should be: https://www.goparamore.io/
Not sure about the little icon in the QR code though

**Comment by preardon** [comment]
@iancooper Thats Great news considering the Logo in the QR is being a Pain in my Arse at the minute, I'll update the QR Code, Also I was playing with a grey background on the QR Code, Thoughts?

**Comment by preardon** [comment]
@iancooper How is this?

![Brighter-Social-Card](https://user-images.githubusercontent.com/7712876/113603279-ab883780-963b-11eb-81d4-45ff6550f1cf.png)

**Comment by iancooper** [comment]
Looks good, though I still think we should point to the  https://www.goparamore.io/ landing page

**Comment by preardon** [comment]
@iancooper do you mean the GitHub URL? I changed the QR Code to point to https://www.goparamore.io/

**Comment by preardon** [comment]
![Brighter-Social-Card](https://user-images.githubusercontent.com/7712876/113605612-d0ca7500-963e-11eb-9665-d5249fae7810.png)

Do you want me to PR this into the Assets/logo Folder?

**Comment by holytshirt** [comment]
Yes please `Assets/logo` Folder is perfect 👍🏼 
Thank you for this!

**Comment by preardon** [comment]
@holytshirt Just Added PR #1480

**Comment by iancooper** [comment]
@preardon and @holytshirt Can we close this now?

**Comment by preardon** [comment]
@iancooper As Far as I am aware this is completed

**Comment by iancooper** [comment]
@holytshirt Feel free to reopen if you to, but closing this one
