### ISSUE TITLE
Rabbit message without headers brings down Dispatcher

### ISSUE THREAD

**Issue by acraven** [BrighterCommand/Brighter#515]
We have a microservice that handles messages from Rabbit via Brighter. We have an example message body that we publish to RabbitMQ to demonstrate our service.

We have discovered by accident that omitting the MessageType header when publishing the message to RabbitMQ brings the Dispatcher to a halt.

Each consumer appears to receive the message once and reply with a NoAck before completing. We are not seeing any exceptions in the logs.

If I recall, the Dispatcher ends when all consumers or jobs have completed.

Once the Dispatcher ends we (currently) have to restart our service. We could obviously monitor the Dispatcher and restart if necessary, but this is less than ideal.

**Comment by holytshirt** [comment]
That is strange, I remember doing  fix for this once where we default to `MessageType.MT_EVENT` is there is nothing in the header.

Secondly if that does error it should be logged as an error and depending on poison message settings. Stop and log an error or log an error, throw away message and continue.

I think there was a big rewrite to this area, I can double check tomorrow.

I know we regularly just write a message to a queue from the rabbitmq ui to test things and don't add headers.

**Comment by acraven** [comment]
The default message type is indeed `MT_EVENT` - this causes a problem in `MessagePumpAsync.DispatchRequest` which throws a `ConfigurationException` since the `TRequest` is an `ICommand`.

`MessagePumpBase.Run` handles `ConfigurationException`, rejecting the message and exiting the message loop.

I haven't got a great deal of knowledge around this library, but I have some thoughts:

* If the message type is being defaulted, I think inferring it from `TRequest` somehow would make sense.
* If it can't be inferred correctly, I think `MT_UNACCEPTABLE` or `MT_NONE` makes sense (however `MT_NONE` is used elsewhere to indicate an absence of message).
* `DispatchRequest` should raise an exception other than `ConfigurationException`. I don't believe the error relates to configuration; perhaps `MessageMappingException` makes more sense, or even a new exception class.

**Comment by iancooper** [comment]
Going to close this one. We default to MT_EVENT if no header as our approach is tolerant reader. This will fail if the requesthandler is expecting a command of course. At this point, we don't know what type it will serialize to. We are on GetMessage and not TranslateMessage, so we can't inspect the type you intend to map too.

My suggestion would be to alter the sender, and if you can't alter the sender, treat it as an event.
