### ISSUE TITLE
Support management and Monitoring of ServiceActivator instances

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#6]
We want both command line and web based monitoring and control of service activator instances. We want to support a view of the message store(s) and sending messages to active instances via a control bus.

The web site should be self-hosted and allow multiple message stores to be viewed in one location. 

The control bus ought to accept over-HTTP control inputs. It needs to publish it's statistics. We envisage using the RestMS as a messaging hub to send messages to Brighter, and to publish stats. Those stats could update the message store web interface to show who consumed messages and ack/reject/requeue.

A simple command line like Curl and WGet could then be used to manage instances. In particular we want to report the passage of messages through, and be able to start and stop individual performers. It would be nice to be able to introduce new performers to handle load. Because it might be a pain to keep formatting and sending RestMS control messages we envisage a python script being developed to help automate this.

The web site could then provide a 'nicer' interface but similar functionality

The goal here is to produce something like Celery management and monitoring tools: http://celery.readthedocs.org/en/latest/userguide/monitoring.html

**Comment by iancooper** [comment]
Ian P is looking at displaying the messages from the message store. 
Ian C is looking at the control bus (initially driving with Fiddler etc, but then with Python)

**Comment by iancooper** [comment]
Rocksteady may have a similar concept: send messages via a control bus that a monitoring service picks up: https://code.google.com/p/rocksteady/

**Comment by penderi** [comment]
A few thoughts abpout this. Whilst looking at montiroing alternatives for Push he found [Bosun]( http://bosun.org/) - Open Source monitoring from the worthy chaps at SO.

## Bosun Archicture
![Bosun Architecture] (http://bosun.org/public/arch.png)

Another useful detail of Bosun is the format used - something exotic called [OpenTSDB](http://opentsdb.net/overview.html). :

## OpenTSDB Architecture
![OpenTSDB](http://opentsdb.net/img/tsdb-architecture.png)

**Comment by iancooper** [comment]
Netflix uses D3 to show Circuit Breaker trips for Hystrix: http://d3js.org/

**Comment by iancooper** [comment]
Cloudwatch can be used to monitor custom metrics: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/publishingMetrics.html

**Comment by iancooper** [comment]
Servo: https://github.com/Netflix/servo/wiki

**Comment by iancooper** [comment]
Windows has switched to ETW from performance counters: https://msdn.microsoft.com/en-us/library/windows/desktop/aa363668%28v=vs.85%29.aspx

**Comment by iancooper** [comment]
Suggestion came in to also consider working with wolfpack: https://wolfpack.codeplex.com/

**Comment by iancooper** [comment]
Another option to look at is a Glimpse plugin: http://getglimpse.com/Extensions/

**Comment by iancooper** [comment]
https://dropwizard.github.io/metrics/3.1.0/getting-started/

**Comment by iancooper** [comment]
Just Eat are using grafana http://grafana.org/ for displaying metrics and Syrene on  top of that to manage alerts: https://github.com/scobal/seyren

**Comment by iancooper** [comment]
See EasyNetQ for an example of integrator traffic: https://github.com/EasyNetQ/EasyNetQ/wiki/Management-API-Introduction

**Comment by iancooper** [comment]
Time has moved on, and although we do create the hose we don't give a useful example of how to use that.

One answer here is Prometheus, we could create a tool (most likely in Python) to consume the RMQ monitoring feed and use that to feed a site that can be exposed to Prometheus (probably written in Flask).

**Comment by iancooper** [comment]
The world has moved on and we probably want to support OpentTracing at this point

**Comment by iancooper** [comment]
Now replaced by #301
