### ISSUE TITLE
Add support for Postgres as a message store

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#71]

**Comment by holytshirt** [comment]
Ouch, that is a pain. 
Does the database do this or the c# progress client?

**Comment by Pothulapati** [comment]
The database does it automatically.

**Comment by holytshirt** [comment]
Ah, see now in the documentation. That's a pain.
How about using the `AT TIME ZONE 'UCT'` in the select?
https://www.postgresql.org/docs/9.1/static/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT

**Comment by Pothulapati** [comment]
I think that's going to work. Will submit a PR once the tests pass. 

Thank You. 👍

**Comment by holytshirt** [comment]
awesome! :+1:

**Comment by Pothulapati** [comment]
There is a clash in the date of the message, the date that PostgreSQL is giving back is one day more than the one that the test expects.
I get the following error 
`Expected date and time to be <2017-08-21 15:15:53>, but found <2017-08-22 02:15:53>.`

And also Why do you decrease the UTC time by one day in MSSQL Server tests?

https://github.com/BrighterCommand/Brighter/blob/ca60978381d969910b729c90b967865702ed0ab1/tests/Paramore.Brighter.Tests/MessageStore/MsSql/When_Writing_A_Message_To_The_Message_Store.cs#L52

**Comment by holytshirt** [comment]
@Pothulapati  looks like that is done just to use  an older date. 
It looks like what you are seeing is a daylight savings issue. Welcome to the wonderful world of dates, I would add working with dates as one of the most painful things in computing.

Try changing your test to 
```
_storedMessage.Header.TimeStamp.AsUtc().Should().Be(_messageEarliest.Header.TimeStamp.AsUtc());
```

**Comment by Pothulapati** [comment]
@holytshirt I tried but the tests still won't pass. There is this same difference between the two dates every time.

After a lot of struggle, This line makes the test pass every time but I'm not sure if it's the correct solution.
```CSharp
 _storedMessage.Header.TimeStamp.AddHours(1).AddDays(-1).ToString("yyyy-mm-dd HH:mm:ss").Should().Be(_messageEarliest.Header.TimeStamp.ToString("yyyy-mm-dd hh:mm:ss"));

```
Thank You.

**Comment by holytshirt** [comment]
think I'm going to have to see the code to see how the day comes from the db and serialised into the object.  As doing that is not correct, even thought the tests are passing :D

**Comment by iancooper** [comment]
Reopened this issue as we don't have an Inbox for Postgres, and we need to confirm this error is gone

**Comment by iancooper** [comment]
Added an inbox via the inbox work
