### ISSUE TITLE
Brighter does not allow messages to be sent as persistent when using RabbitMQ

### ISSUE THREAD

**Issue by wwestrop** [BrighterCommand/Brighter#721]
**Is your feature request related to a problem? Please describe.**
When using RabbitMQ as the messaging gateway, the queues/exchanges it creates can be marked as `durable` and will survive a server failure, but the messages themselves are not sent as `persistent`, so they will be lost.

**Describe the solution you'd like**
I'm not 100% on what the solution would look like, but I imagine some way of configuring this behaviour, either on or off as required, during bootstrap.

**Describe alternatives you've considered**
We are using an active-active pair of servers, so it would take both servers going down to lose messages (my understanding may not be fully correct on this). This would protect us from the lack of persistent messages in many/most cases, but not all. 

**Additional context**
The code I believe responsible is in `Paramore.Brighter.MessagingGateway.RMQ.RmqMessagePublisher.CreateBasicProperties()` [(link to code)](https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter.MessagingGateway.RMQ/RmqMessagePublisher.cs#L175) - the created object never has `Persistent` set and hence always has a default value (which is `false`, as far as I can tell)

**Comment by holytshirt** [comment]
@iancooper I can't remember why we didn't add persistent messages?

**Comment by iancooper** [comment]
Sorry, missed this. At the time we made that choice there were complexities with having queues with persistent messages in some failure scenarios for the RMQ broker. As we store the outgoing message in the message box, we reasoned that it was on balance better to replay.

Much of this has changed, including when RMQ chooses to persist (answer seems to be the flag is not as absolute either way as you might think).

Let's treat this as a but and action.

**Comment by homcl** [comment]
Working on this issue

**Comment by iancooper** [comment]
Awesome. Thank you

**Comment by iancooper** [comment]
Thanks @homcl Closing this one now
