### ISSUE TITLE
Support using Redis for Task Queues

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#77]
Celery does this and it looks like a fairly common requirement. http://celery.readthedocs.org/en/latest/getting-started/brokers/redis.html

We might want to wait on Disque https://github.com/antirez/disque/blob/master/README.md as it builds a proper in-memory distributed work queue via  broker topology on Redis. That fits our needs better as today we rely on our broker for an HA infrastructure for messaging.

**Comment by Jamleck** [comment]
Hi, I was testing the redis messaging getaway you're working on. The library you're using [ServiceStack.Redis](https://github.com/ServiceStack/ServiceStack.Redis) has a Licencing limitation that prevents more than 6000 requests per hour as noted on [their](https://servicestack.net/download) website.  This would require developers to get the licensed version to support any system that has more than 6000 requests per hour. Is it possible to use the StackExchange.Redis library implementation? Below is the exact exception I got.


ServiceStack.LicenseException: 'The free-quota limit on '6000 Redis requests per hour' has been reached. Please see https://servicestack.net to upgrade to a commercial license or visit https://github.com/ServiceStackV3/ServiceStackV3 to revert back to the free ServiceStack v3.'

**Comment by iancooper** [comment]
The StackExchange Redis library won't work as it multiplexes the connection, and this is not compatible with the blocking operations that we need to support Redis queues. However, the stream code might change our minds on this.

Sorry for the long time to reply, ping us on the Gitter channel, as replies here can get lost on GithHub;s interface
